/**
 * @fileoverview Externs generated by dts2as from NextGenActionScript.com
 * @externs
 * @suppress {duplicate}
 */

/**
 * @interface
 */
var FlashPoint = function() {};
/**
 * @type {number}
 */
FlashPoint.prototype.x;

/**
 * @type {number}
 */
FlashPoint.prototype.y;

/**
 * @interface
 * @extends {FlashPoint}
 */
var FlashPoint3D = function() {};
/**
 * @type {number}
 */
FlashPoint3D.prototype.z;

/**
 * @interface
 */
var FlashRectangle = function() {};
/**
 * @type {number}
 */
FlashRectangle.prototype.top;

/**
 * @type {number}
 */
FlashRectangle.prototype.right;

/**
 * @type {number}
 */
FlashRectangle.prototype.bottom;

/**
 * @type {number}
 */
FlashRectangle.prototype.left;

/**
 * @interface
 */
var FlashMatrix = function() {};
/**
 * @type {number}
 */
FlashMatrix.prototype.a;

/**
 * @type {number}
 */
FlashMatrix.prototype.b;

/**
 * @type {number}
 */
FlashMatrix.prototype.c;

/**
 * @type {number}
 */
FlashMatrix.prototype.d;

/**
 * @type {number}
 */
FlashMatrix.prototype.tx;

/**
 * @type {number}
 */
FlashMatrix.prototype.ty;

/**
 * @interface
 */
var FlashFilter = function() {};
/**
 * @type {number}
 */
FlashFilter.prototype.angle;

/**
 * @type {number}
 */
FlashFilter.prototype.blurX;

/**
 * @type {number}
 */
FlashFilter.prototype.blurY;

/**
 * @type {number}
 */
FlashFilter.prototype.brightness;

/**
 * @type {Object}
 */
FlashFilter.prototype.color;

/**
 * @type {number}
 */
FlashFilter.prototype.contrast;

/**
 * @type {number}
 */
FlashFilter.prototype.distance;

/**
 * @type {boolean}
 */
FlashFilter.prototype.enabled;

/**
 * @type {boolean}
 */
FlashFilter.prototype.hideObject;

/**
 * @type {Object}
 */
FlashFilter.prototype.highlightColor;

/**
 * @type {number}
 */
FlashFilter.prototype.hue;

/**
 * @type {boolean}
 */
FlashFilter.prototype.inner;

/**
 * @type {boolean}
 */
FlashFilter.prototype.knockout;

/**
 * @type {string}
 */
FlashFilter.prototype.name;

/**
 * @type {string}
 */
FlashFilter.prototype.quality;

/**
 * @type {number}
 */
FlashFilter.prototype.saturation;

/**
 * @type {Object}
 */
FlashFilter.prototype.shadowColor;

/**
 * @type {number}
 */
FlashFilter.prototype.strength;

/**
 * @type {string}
 */
FlashFilter.prototype.type;

/**
 * @interface
 */
var FlashDocument = function() {};
/**
 * @type {string}
 */
FlashDocument.prototype.accName;

/**
 * @type {boolean}
 */
FlashDocument.prototype.as3AutoDeclare;

/**
 * @type {string}
 */
FlashDocument.prototype.as3Dialect;

/**
 * @type {number}
 */
FlashDocument.prototype.as3ExportFrame;

/**
 * @type {boolean}
 */
FlashDocument.prototype.as3StrictMode;

/**
 * @type {boolean}
 */
FlashDocument.prototype.as3WarningsMode;

/**
 * @type {number}
 */
FlashDocument.prototype.asVersion;

/**
 * @type {boolean}
 */
FlashDocument.prototype.autoLabel;

/**
 * @type {Object}
 */
FlashDocument.prototype.backgroundColor;

/**
 * @type {string}
 */
FlashDocument.prototype.currentPublishProfile;

/**
 * @type {FlashTimeline}
 */
FlashDocument.prototype.currentTimeline;

/**
 * @type {string}
 */
FlashDocument.prototype.description;

/**
 * @type {void}
 */
FlashDocument.prototype.docClass;

/**
 * @type {boolean}
 */
FlashDocument.prototype.forceSimple;

/**
 * @type {number}
 */
FlashDocument.prototype.frameRate;

/**
 * @type {number}
 */
FlashDocument.prototype.height;

/**
 * @type {number}
 */
FlashDocument.prototype.id;

/**
 * @type {FlashLibrary}
 */
FlashDocument.prototype.library;

/**
 * @type {boolean}
 */
FlashDocument.prototype.livePreview;

/**
 * @type {string}
 */
FlashDocument.prototype.name;

/**
 * @type {string}
 */
FlashDocument.prototype.path;

/**
 * @type {string}
 */
FlashDocument.prototype.pathURI;

/**
 * @type {Array}
 */
FlashDocument.prototype.publishProfiles;

/**
 * @type {Array}
 */
FlashDocument.prototype.selection;

/**
 * @type {boolean}
 */
FlashDocument.prototype.silent;

/**
 * @type {Array}
 */
FlashDocument.prototype.timelines;

/**
 * @type {FlashMatrix}
 */
FlashDocument.prototype.viewMatrix;

/**
 * @type {number}
 */
FlashDocument.prototype.width;

/**
 * @type {number}
 */
FlashDocument.prototype.zoomFactor;

/**
 * @param {string} name
 * @param {string} type
 * @param {Object} data
 */
FlashDocument.prototype.addDataToDocument = function(name, type, data) {};

/**
 * @param {string} name
 * @param {string} type
 * @param {Object} data
 */
FlashDocument.prototype.addDataToSelection = function(name, type, data) {};

/**
 * @param {string} filterName
 */
FlashDocument.prototype.addFilter = function(filterName) {};

/**
 * @param {Object} position
 * @param {Object} item
 * @return {boolean}
 */
FlashDocument.prototype.addItem = function(position, item) {};

/**
 * @param {Object} startPoint
 * @param {Object} endpoint
 */
FlashDocument.prototype.addNewLine = function(startPoint, endpoint) {};

/**
 * @param {Object} boundingRectangle
 * @param {boolean=} bSuppressFill
 * @param {boolean=} bSuppressStroke
 */
FlashDocument.prototype.addNewOval = function(boundingRectangle, bSuppressFill, bSuppressStroke) {};

/**
 * @param {Object} boundingRectangle
 * @param {boolean=} bSpupressFill
 * @param {boolean=} bSuppressStroke
 */
FlashDocument.prototype.addNewPrimitiveOval = function(boundingRectangle, bSpupressFill, bSuppressStroke) {};

/**
 * @param {Object} boundingRectangle
 * @param {number} roundness
 * @param {boolean=} bSuppressFill
 * @param {boolean=} bSuppressStroke
 */
FlashDocument.prototype.addNewRectangle = function(boundingRectangle, roundness, bSuppressFill, bSuppressStroke) {};

/**
 * @param {Object} boundingRectangle
 * @param {number} roundness
 * @param {boolean=} bSuppressFill
 * @param {boolean=} bSuppressStroke
 */
FlashDocument.prototype.addNewPrimitiveRectangle = function(boundingRectangle, roundness, bSuppressFill, bSuppressStroke) {};

/**
 * @param {string=} profileName
 */
FlashDocument.prototype.addNewPublishProfile = function(profileName) {};

/**
 * @param {string} name
 * @return {boolean}
 */
FlashDocument.prototype.addNewScene = function(name) {};

/**
 * @param {Object} boundingRectangle
 * @param {string=} text
 */
FlashDocument.prototype.addNewText = function(boundingRectangle, text) {};

/**
 * @param {string} alignmode
 * @param {boolean=} bUseDocumentBounds
 */
FlashDocument.prototype.align = function(alignmode, bUseDocumentBounds) {};

/**
 */
FlashDocument.prototype.allowScreens = function() {};

/**
 * @param {string} arrangeMode
 */
FlashDocument.prototype.arrange = function(arrangeMode) {};

/**
 */
FlashDocument.prototype.breakApart = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.canEditSymbol = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.canRevert = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.canTestMovie = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.canTestScene = function() {};

/**
 * @param {number} oldIndex
 * @param {number} newIndex
 */
FlashDocument.prototype.changeFilterOrder = function(oldIndex, newIndex) {};

/**
 */
FlashDocument.prototype.clipCopy = function() {};

/**
 */
FlashDocument.prototype.clipCut = function() {};

/**
 * @param {boolean=} bInPlace
 */
FlashDocument.prototype.clipPaste = function(bInPlace) {};

/**
 * @param {boolean=} bPromptToSaveChanges
 */
FlashDocument.prototype.close = function(bPromptToSaveChanges) {};

/**
 */
FlashDocument.prototype.convertLinesToFills = function() {};

/**
 * @param {string} type
 * @param {string} name
 * @param {string} registrationPoint
 * @return {FlashSymbolInstance}
 */
FlashDocument.prototype.convertToSymbol = function(type, name, registrationPoint) {};

/**
 */
FlashDocument.prototype.crop = function() {};

/**
 * @param {boolean=} abortIfErrorsExist
 */
FlashDocument.prototype.debugMovie = function(abortIfErrorsExist) {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.deleteEnvelope = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.deletePublishProfile = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.deleteScene = function() {};

/**
 */
FlashDocument.prototype.deleteSelection = function() {};

/**
 */
FlashDocument.prototype.disableAllFilters = function() {};

/**
 * @param {number} filterIndex
 */
FlashDocument.prototype.disableFilter = function(filterIndex) {};

/**
 * @param {number} enabledFilterIndex
 */
FlashDocument.prototype.disableOtherFilters = function(enabledFilterIndex) {};

/**
 * @param {string} distributemode
 * @param {boolean=} bUseDocumentBounds
 */
FlashDocument.prototype.distribute = function(distributemode, bUseDocumentBounds) {};

/**
 */
FlashDocument.prototype.distributeToLayers = function() {};

/**
 * @param {string} name
 * @return {boolean}
 */
FlashDocument.prototype.documentHasData = function(name) {};

/**
 * @param {string=} profileName
 * @return {number}
 */
FlashDocument.prototype.duplicatePublishProfile = function(profileName) {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.duplicateScene = function() {};

/**
 */
FlashDocument.prototype.duplicateSelection = function() {};

/**
 * @param {number} index
 */
FlashDocument.prototype.editScene = function(index) {};

/**
 */
FlashDocument.prototype.enableAllFilters = function() {};

/**
 * @param {number} filterIndex
 */
FlashDocument.prototype.enableFilter = function(filterIndex) {};

/**
 * @param {string=} editMode
 */
FlashDocument.prototype.enterEditMode = function(editMode) {};

/**
 */
FlashDocument.prototype.exitEditMode = function() {};

/**
 * @param {string} fileURI
 * @param {boolean=} bCurrentPNGSettings
 * @param {boolean=} bCurrentFrame
 * @return {boolean}
 */
FlashDocument.prototype.exportPNG = function(fileURI, bCurrentPNGSettings, bCurrentFrame) {};

/**
 * @param {string} fileURI
 */
FlashDocument.prototype.exportPublishProfile = function(fileURI) {};

/**
 * @param {string=} profileName
 * @return {string}
 */
FlashDocument.prototype.exportPublishProfileString = function(profileName) {};

/**
 * @param {string} fileURI
 * @param {boolean=} bCurrentSettings
 */
FlashDocument.prototype.exportSWF = function(fileURI, bCurrentSettings) {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.getAlignToDocument = function() {};

/**
 * @return {string}
 */
FlashDocument.prototype.getBlendMode = function() {};

/**
 * @param {string=} objectToFill
 * @return {FlashFill}
 */
FlashDocument.prototype.getCustomFill = function(objectToFill) {};

/**
 * @param {string=} locationOfStroke
 * @return {FlashStroke}
 */
FlashDocument.prototype.getCustomStroke = function(locationOfStroke) {};

/**
 * @param {string} name
 * @return {Object}
 */
FlashDocument.prototype.getDataFromDocument = function(name) {};

/**
 * @param {string} propertyName
 * @return {Object}
 */
FlashDocument.prototype.getElementProperty = function(propertyName) {};

/**
 * @param {string} attrName
 * @param {number=} startIndex
 * @param {number=} endIndex
 * @return {FlashTextAttrs}
 */
FlashDocument.prototype.getElementTextAttr = function(attrName, startIndex, endIndex) {};

/**
 * @return {Array}
 */
FlashDocument.prototype.getFilters = function() {};

/**
 * @return {string}
 */
FlashDocument.prototype.getMetadata = function() {};

/**
 * @return {string}
 */
FlashDocument.prototype.getMobileSettings = function() {};

/**
 * @return {string}
 */
FlashDocument.prototype.getPlayerVersion = function() {};

/**
 * @return {FlashRectangle}
 */
FlashDocument.prototype.getSelectionRect = function() {};

/**
 * @param {number=} startIndex
 * @param {number=} endIndex
 * @return {string}
 */
FlashDocument.prototype.getTextString = function(startIndex, endIndex) {};

/**
 * @return {FlashTimeline}
 */
FlashDocument.prototype.getTimeline = function() {};

/**
 * @return {FlashPoint}
 */
FlashDocument.prototype.getTransformationPoint = function() {};

/**
 */
FlashDocument.prototype.group = function() {};

/**
 * @param {string} fileURI
 * @param {boolean=} importToLibrary
 */
FlashDocument.prototype.importFile = function(fileURI, importToLibrary) {};

/**
 * @param {string} fileURI
 * @return {number}
 */
FlashDocument.prototype.importPublishProfile = function(fileURI) {};

/**
 * @param {string} xmlString
 * @return {number}
 */
FlashDocument.prototype.importPublishProfileString = function(xmlString) {};

/**
 * @param {string} fileURI
 */
FlashDocument.prototype.importSWF = function(fileURI) {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.intersect = function() {};

/**
 * @param {string} uri
 * @return {Array}
 */
FlashDocument.prototype.loadCuepointXML = function(uri) {};

/**
 * @param {boolean} bWidth
 * @param {boolean} bHeight
 * @param {boolean=} bUseDocumentBounds
 */
FlashDocument.prototype.match = function(bWidth, bHeight, bUseDocumentBounds) {};

/**
 * @param {Object} position
 * @param {boolean} bToggleSel
 * @param {boolean} bShiftSel
 */
FlashDocument.prototype.mouseClick = function(position, bToggleSel, bShiftSel) {};

/**
 * @param {Object} position
 * @param {boolean} bAltDown
 * @param {boolean} bShiftDown
 * @param {boolean} bShiftSelect
 */
FlashDocument.prototype.mouseDblClk = function(position, bAltDown, bShiftDown, bShiftSelect) {};

/**
 * @param {Object} delta
 */
FlashDocument.prototype.moveSelectedBezierPointsBy = function(delta) {};

/**
 * @param {Object} distanceToMove
 */
FlashDocument.prototype.moveSelectionBy = function(distanceToMove) {};

/**
 * @param {number} smoothing
 * @param {boolean} bUseMultiplePasses
 */
FlashDocument.prototype.optimizeCurves = function(smoothing, bUseMultiplePasses) {};

/**
 */
FlashDocument.prototype.publish = function() {};

/**
 * @return {boolean}
 */
FlashDocument.prototype.punch = function() {};

/**
 */
FlashDocument.prototype.removeAllFilters = function() {};

/**
 * @param {string} name
 */
FlashDocument.prototype.removeDataFromDocument = function(name) {};

/**
 * @param {string} name
 */
FlashDocument.prototype.removeDataFromSelection = function(name) {};

/**
 * @param {number} filterIndex
 */
FlashDocument.prototype.removeFilter = function(filterIndex) {};

/**
 * @param {string=} profileNewName
 * @return {boolean}
 */
FlashDocument.prototype.renamePublishProfile = function(profileNewName) {};

/**
 * @param {string} name
 * @return {boolean}
 */
FlashDocument.prototype.renameScene = function(name) {};

/**
 * @param {number} sceneToMove
 * @param {number} sceneToPutItBefore
 */
FlashDocument.prototype.reorderScene = function(sceneToMove, sceneToPutItBefore) {};

/**
 */
FlashDocument.prototype.resetOvalObject = function() {};

/**
 */
FlashDocument.prototype.resetRectangleObject = function() {};

/**
 */
FlashDocument.prototype.resetTransformation = function() {};

/**
 */
FlashDocument.prototype.revert = function() {};

/**
 * @param {Object} xyzCoordinate
 * @param {boolean} bGlobalTransform
 */
FlashDocument.prototype.rotate3DSelection = function(xyzCoordinate, bGlobalTransform) {};

/**
 * @param {number} angle
 * @param {string=} rotationPoint
 */
FlashDocument.prototype.rotateSelection = function(angle, rotationPoint) {};

/**
 * @param {boolean=} bOkToSaveAs
 * @return {boolean}
 */
FlashDocument.prototype.save = function(bOkToSaveAs) {};

/**
 * @param {boolean=} bOkToSaveAs
 * @return {boolean}
 */
FlashDocument.prototype.saveAndCompact = function(bOkToSaveAs) {};

/**
 * @param {number} xScale
 * @param {number} yScale
 * @param {string=} whichCorner
 */
FlashDocument.prototype.scaleSelection = function(xScale, yScale, whichCorner) {};

/**
 */
FlashDocument.prototype.selectAll = function() {};

/**
 */
FlashDocument.prototype.selectNone = function() {};

/**
 * @param {boolean=} bToStage
 */
FlashDocument.prototype.setAlignToDocument = function(bToStage) {};

/**
 * @param {string} mode
 */
FlashDocument.prototype.setBlendMode = function(mode) {};

/**
 * @param {Object} fill
 */
FlashDocument.prototype.setCustomFill = function(fill) {};

/**
 * @param {Object} stroke
 */
FlashDocument.prototype.setCustomStroke = function(stroke) {};

/**
 * @param {string} property
 * @param {number} value
 */
FlashDocument.prototype.setElementProperty = function(property, value) {};

/**
 * @param {string} attrName
 * @param {Object} attrValue
 * @param {number=} startIndex
 * @param {number=} endIndex
 * @return {boolean}
 */
FlashDocument.prototype.setElementTextAttr = function(attrName, attrValue, startIndex, endIndex) {};

/**
 * @param {Object} color
 */
FlashDocument.prototype.setFillColor = function(color) {};

/**
 * @param {string} property
 * @param {number} filterIndex
 * @param {Object} value
 */
FlashDocument.prototype.setFilterProperty = function(property, filterIndex, value) {};

/**
 * @param {Array} filterArray
 */
FlashDocument.prototype.setFilters = function(filterArray) {};

/**
 * @param {number} opacity
 */
FlashDocument.prototype.setInstanceAlpha = function(opacity) {};

/**
 * @param {number} brightness
 */
FlashDocument.prototype.setInstanceBrightness = function(brightness) {};

/**
 * @param {Object} color
 * @param {number} strength
 */
FlashDocument.prototype.setInstanceTint = function(color, strength) {};

/**
 * @param {string} strMetadata
 * @return {boolean}
 */
FlashDocument.prototype.setMetadata = function(strMetadata) {};

/**
 * @param {string} xmlString
 * @return {boolean}
 */
FlashDocument.prototype.setMobileSettings = function(xmlString) {};

/**
 * @param {string} propertyName
 * @param {Object} value
 */
FlashDocument.prototype.setOvalObjectProperty = function(propertyName, value) {};

/**
 * @param {string} version
 * @return {boolean}
 */
FlashDocument.prototype.setPlayerVersion = function(version) {};

/**
 * @param {string} propertyName
 * @param {Object} value
 */
FlashDocument.prototype.setRectangleObjectProperty = function(propertyName, value) {};

/**
 * @param {Object} boundingRectangle
 * @param {boolean=} bContactSensitiveSelection
 */
FlashDocument.prototype.setSelectionBounds = function(boundingRectangle, bContactSensitiveSelection) {};

/**
 * @param {Object} rect
 * @param {boolean=} bReplaceCurrentSelection
 * @param {boolean=} bContactSensitiveSelection
 */
FlashDocument.prototype.setSelectionRect = function(rect, bReplaceCurrentSelection, bContactSensitiveSelection) {};

/**
 * @param {Object} point
 */
FlashDocument.prototype.setStageVanishingPoint = function(point) {};

/**
 * @param {number} angle
 */
FlashDocument.prototype.setStageViewAngle = function(angle) {};

/**
 * @param {Object} color
 * @param {number} size
 * @param {string} strokeType
 */
FlashDocument.prototype.setStroke = function(color, size, strokeType) {};

/**
 * @param {Object} color
 */
FlashDocument.prototype.setStrokeColor = function(color) {};

/**
 * @param {number} size
 */
FlashDocument.prototype.setStrokeSize = function(size) {};

/**
 * @param {string} strokeType
 */
FlashDocument.prototype.setStrokeStyle = function(strokeType) {};

/**
 * @param {Object} boundingRectangle
 * @return {boolean}
 */
FlashDocument.prototype.setTextRectangle = function(boundingRectangle) {};

/**
 * @param {number} startIndex
 * @param {number} endIndex
 * @return {boolean}
 */
FlashDocument.prototype.setTextSelection = function(startIndex, endIndex) {};

/**
 * @param {string} text
 * @param {number=} startIndex
 * @param {number=} endIndex
 * @return {boolean}
 */
FlashDocument.prototype.setTextString = function(text, startIndex, endIndex) {};

/**
 * @param {Object} transformationPoint
 */
FlashDocument.prototype.setTransformationPoint = function(transformationPoint) {};

/**
 * @param {number} xSkew
 * @param {number} ySkew
 * @param {string=} whichEdge
 */
FlashDocument.prototype.skewSelection = function(xSkew, ySkew, whichEdge) {};

/**
 */
FlashDocument.prototype.smoothSelection = function() {};

/**
 * @param {string} direction
 * @param {boolean=} bUseDocumentBounds
 */
FlashDocument.prototype.space = function(direction, bUseDocumentBounds) {};

/**
 */
FlashDocument.prototype.straightenSelection = function() {};

/**
 * @param {string} name
 */
FlashDocument.prototype.swapElement = function(name) {};

/**
 */
FlashDocument.prototype.swapStrokeAndFill = function() {};

/**
 */
FlashDocument.prototype.testMovie = function() {};

/**
 */
FlashDocument.prototype.testScene = function() {};

/**
 * @param {number} threshold
 * @param {number} minimumArea
 * @param {string} curveFit
 * @param {string} cornerThreshold
 */
FlashDocument.prototype.traceBitmap = function(threshold, minimumArea, curveFit, cornerThreshold) {};

/**
 * @param {number} a
 * @param {number} b
 * @param {number} c
 * @param {number} d
 */
FlashDocument.prototype.transformSelection = function(a, b, c, d) {};

/**
 */
FlashDocument.prototype.unGroup = function() {};

/**
 */
FlashDocument.prototype.union = function() {};

/**
 */
FlashDocument.prototype.unlockAllElements = function() {};

/**
 * @param {string} fileURI
 * @return {Object}
 */
FlashDocument.prototype.xmlPanel = function(fileURI) {};

/**
 * @interface
 */
var FlashText = function() {};
/**
 * @type {string}
 */
FlashText.prototype.accName;

/**
 * @type {number}
 */
FlashText.prototype.antiAliasSharpness;

/**
 * @type {number}
 */
FlashText.prototype.antiAliasThickness;

/**
 * @type {boolean}
 */
FlashText.prototype.autoExpand;

/**
 * @type {boolean}
 */
FlashText.prototype.border;

/**
 * @type {string}
 */
FlashText.prototype.description;

/**
 * @type {string}
 */
FlashText.prototype.embeddedCharacters;

/**
 */
FlashText.prototype.getTextAttr = function() {};

/**
 */
FlashText.prototype.getTextString = function() {};

/**
 */
FlashText.prototype.setTextAttr = function() {};

/**
 */
FlashText.prototype.setTextString = function() {};

/**
 * @interface
 * @extends {FlashText}
 */
var FlashTextAttrs = function() {};
/**
 * @type {boolean}
 */
FlashTextAttrs.prototype.aliasText;

/**
 * @type {string}
 */
FlashTextAttrs.prototype.alignment;

/**
 * @type {boolean}
 */
FlashTextAttrs.prototype.autoKern;

/**
 * @type {boolean}
 */
FlashTextAttrs.prototype.bold;

/**
 * @type {string}
 */
FlashTextAttrs.prototype.characterPosition;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.characterSpacing;

/**
 * @type {string}
 */
FlashTextAttrs.prototype.face;

/**
 * @type {Object}
 */
FlashTextAttrs.prototype.fillColor;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.indent;

/**
 * @type {boolean}
 */
FlashTextAttrs.prototype.italic;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.leftMargin;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.letterSpacing;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.lineSpacing;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.rightMargin;

/**
 * @type {boolean}
 */
FlashTextAttrs.prototype.rotation;

/**
 * @type {number}
 */
FlashTextAttrs.prototype.size;

/**
 * @type {string}
 */
FlashTextAttrs.prototype.target;

/**
 * @type {string}
 */
FlashTextAttrs.prototype.url;

/**
 * @interface
 */
var FlashFLfile = function() {};
/**
 * @param {string} fileURI
 * @param {string} copyURI
 * @return {boolean}
 */
FlashFLfile.prototype.copy = function(fileURI, copyURI) {};

/**
 * @param {string} folderURI
 * @return {boolean}
 */
FlashFLfile.prototype.createFolder = function(folderURI) {};

/**
 * @param {string} fileURI
 * @return {boolean}
 */
FlashFLfile.prototype.exists = function(fileURI) {};

/**
 * @param {string} fileOrFolderURI
 * @return {string}
 */
FlashFLfile.prototype.getAttributes = function(fileOrFolderURI) {};

/**
 * @param {string} fileOrFolderURI
 * @return {string}
 */
FlashFLfile.prototype.getCreationDate = function(fileOrFolderURI) {};

/**
 * @param {string} fileOrFolderURI
 * @return {Date}
 */
FlashFLfile.prototype.getCreationDateObj = function(fileOrFolderURI) {};

/**
 * @param {string} fileOrFolderURI
 * @return {string}
 */
FlashFLfile.prototype.getModificationDate = function(fileOrFolderURI) {};

/**
 * @param {string} fileOrFolderURI
 * @return {Date}
 */
FlashFLfile.prototype.getModificationDateObj = function(fileOrFolderURI) {};

/**
 * @param {string} fileURI
 * @return {number}
 */
FlashFLfile.prototype.getSize = function(fileURI) {};

/**
 * @param {string} folderURI
 * @param {boolean=} filesOrDirectories
 * @return {Array}
 */
FlashFLfile.prototype.listFolder = function(folderURI, filesOrDirectories) {};

/**
 * @param {string} fileName
 * @return {string}
 */
FlashFLfile.prototype.platformPathToURI = function(fileName) {};

/**
 * @param {string} fileOrFolderURI
 * @return {string}
 */
FlashFLfile.prototype.read = function(fileOrFolderURI) {};

/**
 * @param {string} fileOrFolderURI
 * @return {boolean}
 */
FlashFLfile.prototype.remove = function(fileOrFolderURI) {};

/**
 * @param {string} fileURI
 * @param {string} strAttrs
 * @return {boolean}
 */
FlashFLfile.prototype.setAttributes = function(fileURI, strAttrs) {};

/**
 * @param {string} fileURI
 * @return {string}
 */
FlashFLfile.prototype.uriToPlatformPath = function(fileURI) {};

/**
 * @param {string} fileURI
 * @param {string} textToWrite
 * @param {string=} strAppendMode
 * @return {boolean}
 */
FlashFLfile.prototype.write = function(fileURI, textToWrite, strAppendMode) {};

/**
 * @interface
 */
var FlashSoundItem = function() {};
/**
 * @type {string}
 */
FlashSoundItem.prototype.bitRate;

/**
 * @type {string}
 */
FlashSoundItem.prototype.bits;

/**
 * @type {string}
 */
FlashSoundItem.prototype.compressionType;

/**
 * @type {boolean}
 */
FlashSoundItem.prototype.convertStereoToMono;

/**
 * @type {string}
 */
FlashSoundItem.prototype.fileLastModifiedDate;

/**
 * @type {string}
 */
FlashSoundItem.prototype.originalCompressionType;

/**
 * @type {string}
 */
FlashSoundItem.prototype.quality;

/**
 * @type {string}
 */
FlashSoundItem.prototype.sampleRate;

/**
 * @type {boolean}
 */
FlashSoundItem.prototype.sourceFileExists;

/**
 * @param {string} fileURI
 * @return {boolean}
 */
FlashSoundItem.prototype.exportToFile = function(fileURI) {};

/**
 * @interface
 */
var FlashInstance = function() {};
/**
 * @interface
 */
var _FlashBitmap = function() {};
/**
 * @type {void}
 */
_FlashBitmap.prototype.width;

/**
 * @type {void}
 */
_FlashBitmap.prototype.height;

/**
 * @type {void}
 */
_FlashBitmap.prototype.depth;

/**
 * @type {void}
 */
_FlashBitmap.prototype.bits;

/**
 * @interface
 */
var FlashBitmapInstance = function() {};
/**
 * @type {number}
 */
FlashBitmapInstance.prototype.hPixels;

/**
 * @type {number}
 */
FlashBitmapInstance.prototype.vPixels;

/**
 * @return {_FlashBitmap}
 */
FlashBitmapInstance.prototype.getBits = function() {};

/**
 * @param {Object} bitmap
 */
FlashBitmapInstance.prototype.setBits = function(bitmap) {};

/**
 * @interface
 */
var FlashCompiledClipInstance = function() {};
/**
 * @type {string}
 */
FlashCompiledClipInstance.prototype.accName;

/**
 * @type {string}
 */
FlashCompiledClipInstance.prototype.actionScript;

/**
 * @type {string}
 */
FlashCompiledClipInstance.prototype.description;

/**
 * @type {boolean}
 */
FlashCompiledClipInstance.prototype.forceSimple;

/**
 * @type {string}
 */
FlashCompiledClipInstance.prototype.shortcut;

/**
 * @type {boolean}
 */
FlashCompiledClipInstance.prototype.silent;

/**
 * @type {number}
 */
FlashCompiledClipInstance.prototype.tabIndex;

/**
 * @interface
 */
var FlashSymbolInstance = function() {};
/**
 * @type {string}
 */
FlashSymbolInstance.prototype.accName;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.actionScript;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.backgroundColor;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.bitmapRenderMode;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.blendMode;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.buttonTracking;

/**
 * @type {boolean}
 */
FlashSymbolInstance.prototype.cacheAsBitmap;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorAlphaAmount;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorAlphaPercent;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorBlueAmount;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorBluePercent;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorGreenAmount;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorGreenPercent;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.colorMode;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorRedAmount;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.colorRedPercent;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.description;

/**
 * @type {Array}
 */
FlashSymbolInstance.prototype.filters;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.firstFrame;

/**
 * @type {boolean}
 */
FlashSymbolInstance.prototype.forceSimple;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.loop;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.shortcut;

/**
 * @type {boolean}
 */
FlashSymbolInstance.prototype.silent;

/**
 * @type {string}
 */
FlashSymbolInstance.prototype.symbolType;

/**
 * @type {number}
 */
FlashSymbolInstance.prototype.tabIndex;

/**
 * @type {boolean}
 */
FlashSymbolInstance.prototype.useBackgroundColor;

/**
 * @type {boolean}
 */
FlashSymbolInstance.prototype.visible;

/**
 * @interface
 */
var FlashComponentInstance = function() {};
/**
 * @type {Array}
 */
FlashComponentInstance.prototype.parameters;

/**
 * @interface
 * @extends {FlashOval}
 */
var FlashShape = function() {};
/**
 * @type {Array}
 */
FlashShape.prototype.contours;

/**
 * @type {Array}
 */
FlashShape.prototype.edges;

/**
 * @type {boolean}
 */
FlashShape.prototype.isDrawingObject;

/**
 * @type {boolean}
 */
FlashShape.prototype.isGroup;

/**
 * @type {boolean}
 */
FlashShape.prototype.isOvalObject;

/**
 * @type {boolean}
 */
FlashShape.prototype.isRectangleObject;

/**
 * @type {Array}
 */
FlashShape.prototype.members;

/**
 * @type {number}
 */
FlashShape.prototype.numCubicSegments;

/**
 * @type {Array}
 */
FlashShape.prototype.vertices;

/**
 * @param {number} cubicSegmentIndex
 * @return {Array}
 */
FlashShape.prototype.getCubicSegmentPoints = function(cubicSegmentIndex) {};

/**
 */
FlashShape.prototype.beginEdit = function() {};

/**
 * @param {number} index
 */
FlashShape.prototype.deleteEdge = function(index) {};

/**
 */
FlashShape.prototype.endEdit = function() {};

/**
 * @interface
 * @extends {FlashInstance}
 * @extends {FlashBitmapInstance}
 * @extends {FlashCompiledClipInstance}
 * @extends {FlashSymbolInstance}
 * @extends {FlashComponentInstance}
 * @extends {FlashShape}
 */
var FlashElement = function() {};
/**
 * @type {number}
 */
FlashElement.prototype.depth;

/**
 * @type {string}
 */
FlashElement.prototype.elementType;

/**
 * @type {number}
 */
FlashElement.prototype.height;

/**
 * @type {FlashLayer}
 */
FlashElement.prototype.layer;

/**
 * @type {number}
 */
FlashElement.prototype.left;

/**
 * @type {boolean}
 */
FlashElement.prototype.locked;

/**
 * @type {FlashMatrix}
 */
FlashElement.prototype.matrix;

/**
 * @type {string}
 */
FlashElement.prototype.name;

/**
 * @type {number}
 */
FlashElement.prototype.rotation;

/**
 * @type {number}
 */
FlashElement.prototype.scaleX;

/**
 * @type {number}
 */
FlashElement.prototype.scaleY;

/**
 * @type {boolean}
 */
FlashElement.prototype.selected;

/**
 * @type {number}
 */
FlashElement.prototype.skewX;

/**
 * @type {number}
 */
FlashElement.prototype.skewY;

/**
 * @type {number}
 */
FlashElement.prototype.top;

/**
 * @type {number}
 */
FlashElement.prototype.transformX;

/**
 * @type {number}
 */
FlashElement.prototype.transformY;

/**
 * @type {number}
 */
FlashElement.prototype.width;

/**
 * @type {number}
 */
FlashElement.prototype.x;

/**
 * @type {number}
 */
FlashElement.prototype.y;

/**
 * @param {string} name
 * @return {Object}
 */
FlashElement.prototype.getPersistentData = function(name) {};

/**
 * @return {FlashPoint}
 */
FlashElement.prototype.getTransformationPoint = function() {};

/**
 * @param {string} name
 * @return {boolean}
 */
FlashElement.prototype.hasPersistentData = function(name) {};

/**
 * @param {string} name
 */
FlashElement.prototype.removePersistentData = function(name) {};

/**
 * @param {string} name
 * @param {string} type
 * @param {Object} value
 */
FlashElement.prototype.setPersistentData = function(name, type, value) {};

/**
 * @param {Object} transformationPoint
 */
FlashElement.prototype.setTransformationPoint = function(transformationPoint) {};

/**
 * @interface
 */
var FlashFrame = function() {};
/**
 * @type {void}
 */
FlashFrame.prototype.actionScript;

/**
 * @type {void}
 */
FlashFrame.prototype.duration;

/**
 * @type {Array}
 */
FlashFrame.prototype.elements;

/**
 * @type {void}
 */
FlashFrame.prototype.hasCustomEase;

/**
 * @type {void}
 */
FlashFrame.prototype.labelType;

/**
 * @type {void}
 */
FlashFrame.prototype.motionTweenOrientToPath;

/**
 * @type {void}
 */
FlashFrame.prototype.motionTweenRotate;

/**
 * @type {void}
 */
FlashFrame.prototype.motionTweenRotateTimes;

/**
 * @type {void}
 */
FlashFrame.prototype.motionTweenScale;

/**
 * @type {void}
 */
FlashFrame.prototype.motionTweenSnap;

/**
 * @type {void}
 */
FlashFrame.prototype.motionTweenSync;

/**
 * @type {void}
 */
FlashFrame.prototype.name;

/**
 * @type {void}
 */
FlashFrame.prototype.shapeTweenBlend;

/**
 * @type {void}
 */
FlashFrame.prototype.soundEffect;

/**
 * @type {FlashSoundItem}
 */
FlashFrame.prototype.soundLibraryItem;

/**
 * @type {void}
 */
FlashFrame.prototype.soundLoop;

/**
 * @type {void}
 */
FlashFrame.prototype.soundLoopMode;

/**
 * @type {void}
 */
FlashFrame.prototype.soundName;

/**
 * @type {void}
 */
FlashFrame.prototype.soundSync;

/**
 * @type {void}
 */
FlashFrame.prototype.startFrame;

/**
 * @type {void}
 */
FlashFrame.prototype.tweenEasing;

/**
 * @type {void}
 */
FlashFrame.prototype.tweenType;

/**
 * @type {void}
 */
FlashFrame.prototype.useSingleEaseCurve;

/**
 */
FlashFrame.prototype.getCustomEase = function() {};

/**
 */
FlashFrame.prototype.setCustomEase = function() {};

/**
 * @interface
 */
var FlashSymbolItem = function() {};
/**
 * @type {boolean}
 */
FlashSymbolItem.prototype.scalingGrid;

/**
 * @type {FlashRectangle}
 */
FlashSymbolItem.prototype.scalingGridRect;

/**
 * @type {boolean}
 */
FlashSymbolItem.prototype.sourceAutoUpdate;

/**
 * @type {string}
 */
FlashSymbolItem.prototype.sourceFilePath;

/**
 * @type {string}
 */
FlashSymbolItem.prototype.sourceLibraryName;

/**
 * @type {string}
 */
FlashSymbolItem.prototype.symbolType;

/**
 * @type {FlashTimeline}
 */
FlashSymbolItem.prototype.timeline;

/**
 */
FlashSymbolItem.prototype.convertToCompiledClip = function() {};

/**
 * @param {string} outputURI
 */
FlashSymbolItem.prototype.exportSWC = function(outputURI) {};

/**
 * @param {string} outputURI
 */
FlashSymbolItem.prototype.exportSWF = function(outputURI) {};

/**
 * @interface
 */
var FlashFolderItem = function() {};
/**
 * @interface
 */
var FlashFontItem = function() {};
/**
 * @type {boolean}
 */
FlashFontItem.prototype.bitmap;

/**
 * @type {boolean}
 */
FlashFontItem.prototype.bold;

/**
 * @type {string}
 */
FlashFontItem.prototype.embeddedCharacters;

/**
 * @type {string}
 */
FlashFontItem.prototype.embedRanges;

/**
 * @type {boolean}
 */
FlashFontItem.prototype.embedVariantGlyphs;

/**
 * @type {string}
 */
FlashFontItem.prototype.font;

/**
 * @type {boolean}
 */
FlashFontItem.prototype.isDefineFont4Symbol;

/**
 * @type {boolean}
 */
FlashFontItem.prototype.italic;

/**
 * @type {number}
 */
FlashFontItem.prototype.size;

/**
 * @interface
 */
var FlashVideoItem = function() {};
/**
 * @type {string}
 */
FlashVideoItem.prototype.fileLastModifiedDate;

/**
 * @type {boolean}
 */
FlashVideoItem.prototype.sourceFileExists;

/**
 * @type {boolean}
 */
FlashVideoItem.prototype.sourceFileIsCurrent;

/**
 * @type {string}
 */
FlashVideoItem.prototype.sourceFilePath;

/**
 * @type {string}
 */
FlashVideoItem.prototype.videoType;

/**
 * @param {string} fileURI
 * @return {boolean}
 */
FlashVideoItem.prototype.exportToFLV = function(fileURI) {};

/**
 * @interface
 */
var FlashBitmapItem = function() {};
/**
 * @type {boolean}
 */
FlashBitmapItem.prototype.allowSmoothing;

/**
 * @type {string}
 */
FlashBitmapItem.prototype.compressionType;

/**
 * @type {string}
 */
FlashBitmapItem.prototype.fileLastModifiedDate;

/**
 * @type {string}
 */
FlashBitmapItem.prototype.originalCompressionType;

/**
 * @type {boolean}
 */
FlashBitmapItem.prototype.sourceFileExists;

/**
 * @type {boolean}
 */
FlashBitmapItem.prototype.sourceFileIsCurrent;

/**
 * @type {string}
 */
FlashBitmapItem.prototype.sourceFilePath;

/**
 * @type {boolean}
 */
FlashBitmapItem.prototype.useDeblocking;

/**
 * @type {boolean}
 */
FlashBitmapItem.prototype.useImportedJPEGQuality;

/**
 * @param {string} fileURI
 * @return {boolean}
 */
FlashBitmapItem.prototype.exportToFile = function(fileURI) {};

/**
 * @interface
 * @extends {FlashSymbolItem}
 * @extends {FlashFolderItem}
 * @extends {FlashFontItem}
 * @extends {FlashSoundItem}
 * @extends {FlashVideoItem}
 * @extends {FlashBitmapItem}
 * @extends {FlashBitmapItem}
 */
var FlashItem = function() {};
/**
 * @type {string}
 */
FlashItem.prototype.itemType;

/**
 * @type {string}
 */
FlashItem.prototype.linkageBaseClass;

/**
 * @type {string}
 */
FlashItem.prototype.linkageClassName;

/**
 * @type {boolean}
 */
FlashItem.prototype.linkageExportForAS;

/**
 * @type {boolean}
 */
FlashItem.prototype.linkageExportForRS;

/**
 * @type {boolean}
 */
FlashItem.prototype.linkageExportInFirstFrame;

/**
 * @type {string}
 */
FlashItem.prototype.linkageIdentifier;

/**
 * @type {boolean}
 */
FlashItem.prototype.linkageImportForRS;

/**
 * @type {string}
 */
FlashItem.prototype.linkageURL;

/**
 * @type {string}
 */
FlashItem.prototype.name;

/**
 * @param {string} name
 * @param {string} type
 * @param {Object} data
 */
FlashItem.prototype.addData = function(name, type, data) {};

/**
 * @param {string} name
 * @return {Object}
 */
FlashItem.prototype.getData = function(name) {};

/**
 * @param {string} name
 * @return {boolean}
 */
FlashItem.prototype.hasData = function(name) {};

/**
 * @param {string} name
 */
FlashItem.prototype.removeData = function(name) {};

/**
 * @interface
 */
var FlashLayer = function() {};
/**
 * @type {Object}
 */
FlashLayer.prototype.color;

/**
 * @type {number}
 */
FlashLayer.prototype.frameCount;

/**
 * @type {Array}
 */
FlashLayer.prototype.frames;

/**
 * @type {number}
 */
FlashLayer.prototype.height;

/**
 * @type {string}
 */
FlashLayer.prototype.layerType;

/**
 * @type {boolean}
 */
FlashLayer.prototype.locked;

/**
 * @type {string}
 */
FlashLayer.prototype.name;

/**
 * @type {boolean}
 */
FlashLayer.prototype.outline;

/**
 * @type {FlashLayer}
 */
FlashLayer.prototype.parentLayer;

/**
 * @type {boolean}
 */
FlashLayer.prototype.visible;

/**
 * @interface
 */
var FlashLibrary = function() {};
/**
 * @type {Array}
 */
FlashLibrary.prototype.items;

/**
 * @param {Object} position
 * @param {string=} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.addItemToDocument = function(position, namePath) {};

/**
 * @param {string} type
 * @param {string=} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.addNewItem = function(type, namePath) {};

/**
 * @param {string=} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.deleteItem = function(namePath) {};

/**
 * @param {string} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.duplicateItem = function(namePath) {};

/**
 * @param {string=} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.editItem = function(namePath) {};

/**
 * @param {boolean} bExpand
 * @param {boolean=} bRecurseNestedParents
 * @param {string=} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.expandFolder = function(bExpand, bRecurseNestedParents, namePath) {};

/**
 * @param {string} namePath
 * @return {number}
 */
FlashLibrary.prototype.findItemIndex = function(namePath) {};

/**
 * @param {string} property
 * @return {string}
 */
FlashLibrary.prototype.getItemProperty = function(property) {};

/**
 * @param {string=} namePath
 * @return {string}
 */
FlashLibrary.prototype.getItemType = function(namePath) {};

/**
 * @return {Array}
 */
FlashLibrary.prototype.getSelectedItems = function() {};

/**
 * @param {string} linkageName
 * @param {Array} swfData
 * @param {string=} libName
 */
FlashLibrary.prototype.importEmbeddedSWF = function(linkageName, swfData, libName) {};

/**
 * @param {string} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.itemExists = function(namePath) {};

/**
 * @param {string} folderPath
 * @param {string=} itemToMove
 * @param {boolean=} bReplace
 * @return {boolean}
 */
FlashLibrary.prototype.moveToFolder = function(folderPath, itemToMove, bReplace) {};

/**
 * @param {string=} folderPath
 * @return {boolean}
 */
FlashLibrary.prototype.newFolder = function(folderPath) {};

/**
 * @param {string} name
 * @return {boolean}
 */
FlashLibrary.prototype.renameItem = function(name) {};

/**
 * @param {boolean=} bSelectAll
 */
FlashLibrary.prototype.selectAll = function(bSelectAll) {};

/**
 * @param {string} namePath
 * @param {boolean=} bReplaceCurrentSelection
 * @param {boolean=} bSelect
 * @return {boolean}
 */
FlashLibrary.prototype.selectItem = function(namePath, bReplaceCurrentSelection, bSelect) {};

/**
 */
FlashLibrary.prototype.selectNone = function() {};

/**
 * @param {string} property
 * @param {Object} value
 */
FlashLibrary.prototype.setItemProperty = function(property, value) {};

/**
 * @param {string} namePath
 * @return {boolean}
 */
FlashLibrary.prototype.updateItem = function(namePath) {};

/**
 * @interface
 */
var FlashMath = function() {};
/**
 * @param {Object} mat1
 * @param {Object} mat2
 * @return {FlashMatrix}
 */
FlashMath.prototype.concatMatrix = function(mat1, mat2) {};

/**
 * @param {Object} mat
 * @return {FlashMatrix}
 */
FlashMath.prototype.invertMatrix = function(mat) {};

/**
 * @param {Object} pt1
 * @param {Object} pt2
 * @return {number}
 */
FlashMath.prototype.pointDistance = function(pt1, pt2) {};

/**
 * @interface
 */
var FlashOutputPanel = function() {};
/**
 */
FlashOutputPanel.prototype.clear = function() {};

/**
 * @param {string} fileURI
 * @param {boolean=} bAppendToFile
 * @param {boolean=} bUseSystemEncoding
 */
FlashOutputPanel.prototype.save = function(fileURI, bAppendToFile, bUseSystemEncoding) {};

/**
 * @param {string} message
 */
FlashOutputPanel.prototype.trace = function(message) {};

/**
 * @interface
 */
var FlashHalfEdge = function() {};
/**
 * @type {number}
 */
FlashHalfEdge.prototype.id;

/**
 * @type {number}
 */
FlashHalfEdge.prototype.index;

/**
 * @return {FlashEdge}
 */
FlashHalfEdge.prototype.getEdge = function() {};

/**
 * @return {FlashHalfEdge}
 */
FlashHalfEdge.prototype.getNext = function() {};

/**
 * @return {FlashHalfEdge}
 */
FlashHalfEdge.prototype.getOppositeHalfEdge = function() {};

/**
 * @return {FlashHalfEdge}
 */
FlashHalfEdge.prototype.getPrev = function() {};

/**
 * @return {FlashVertex}
 */
FlashHalfEdge.prototype.getVertex = function() {};

/**
 * @interface
 */
var FlashOval = function() {};
/**
 * @type {boolean}
 */
FlashOval.prototype.closePath;

/**
 * @type {number}
 */
FlashOval.prototype.endAngle;

/**
 * @type {number}
 */
FlashOval.prototype.innerRadius;

/**
 * @type {number}
 */
FlashOval.prototype.startAngle;

/**
 * @interface
 */
var FlashFill = function() {};
/**
 * @type {boolean}
 */
FlashFill.prototype.bitmapIsClipped;

/**
 * @type {string}
 */
FlashFill.prototype.bitmapPath;

/**
 * @type {Object}
 */
FlashFill.prototype.color;

/**
 * @type {Array}
 */
FlashFill.prototype.colorArray;

/**
 * @type {number}
 */
FlashFill.prototype.focalPoint;

/**
 * @type {boolean}
 */
FlashFill.prototype.linearRGB;

/**
 * @type {FlashMatrix}
 */
FlashFill.prototype.matrix;

/**
 * @type {string}
 */
FlashFill.prototype.overflow;

/**
 * @type {Array}
 */
FlashFill.prototype.posArray;

/**
 * @type {string}
 */
FlashFill.prototype.style;

/**
 * @interface
 */
var FlashContour = function() {};
/**
 * @type {FlashFill}
 */
FlashContour.prototype.fill;

/**
 * @type {boolean}
 */
FlashContour.prototype.interior;

/**
 * @type {number}
 */
FlashContour.prototype.orientation;

/**
 * @return {FlashHalfEdge}
 */
FlashContour.prototype.getHalfEdge = function() {};

/**
 * @interface
 */
var FlashStroke = function() {};
/**
 * @type {boolean}
 */
FlashStroke.prototype.breakAtCorners;

/**
 * @type {string}
 */
FlashStroke.prototype.capType;

/**
 * @type {Object}
 */
FlashStroke.prototype.color;

/**
 * @type {string}
 */
FlashStroke.prototype.curve;

/**
 * @type {number}
 */
FlashStroke.prototype.dash1;

/**
 * @type {number}
 */
FlashStroke.prototype.dash2;

/**
 * @type {string}
 */
FlashStroke.prototype.density;

/**
 * @type {string}
 */
FlashStroke.prototype.dotSize;

/**
 * @type {number}
 */
FlashStroke.prototype.dotSpace;

/**
 * @type {string}
 */
FlashStroke.prototype.hatchThickness;

/**
 * @type {string}
 */
FlashStroke.prototype.jiggle;

/**
 * @type {string}
 */
FlashStroke.prototype.joinType;

/**
 * @type {string}
 */
FlashStroke.prototype.length;

/**
 * @type {number}
 */
FlashStroke.prototype.miterLimit;

/**
 * @type {string}
 */
FlashStroke.prototype.pattern;

/**
 * @type {string}
 */
FlashStroke.prototype.rotate;

/**
 * @type {string}
 */
FlashStroke.prototype.scaleType;

/**
 * @type {FlashFill}
 */
FlashStroke.prototype.shapeFill;

/**
 * @type {string}
 */
FlashStroke.prototype.space;

/**
 * @type {boolean}
 */
FlashStroke.prototype.strokeHinting;

/**
 * @type {string}
 */
FlashStroke.prototype.style;

/**
 * @type {number}
 */
FlashStroke.prototype.thickness;

/**
 * @type {string}
 */
FlashStroke.prototype.variation;

/**
 * @type {string}
 */
FlashStroke.prototype.waveHeight;

/**
 * @type {string}
 */
FlashStroke.prototype.waveLength;

/**
 * @interface
 */
var FlashEdge = function() {};
/**
 * @type {number}
 */
FlashEdge.prototype.cubicSegmentIndex;

/**
 * @type {number}
 */
FlashEdge.prototype.id;

/**
 * @type {boolean}
 */
FlashEdge.prototype.isLine;

/**
 * @type {FlashStroke}
 */
FlashEdge.prototype.stroke;

/**
 * @param {number} i
 * @return {FlashPoint}
 */
FlashEdge.prototype.getControl = function(i) {};

/**
 * @param {number} index
 * @return {FlashHalfEdge}
 */
FlashEdge.prototype.getHalfEdge = function(index) {};

/**
 * @param {number} index
 * @param {number} x
 * @param {number} y
 */
FlashEdge.prototype.setControl = function(index, x, y) {};

/**
 * @param {number} t
 */
FlashEdge.prototype.splitEdge = function(t) {};

/**
 * @interface
 */
var FlashVertex = function() {};
/**
 * @type {number}
 */
FlashVertex.prototype.x;

/**
 * @type {number}
 */
FlashVertex.prototype.y;

/**
 * @return {FlashHalfEdge}
 */
FlashVertex.prototype.getHalfEdge = function() {};

/**
 * @param {number} x
 * @param {number} y
 */
FlashVertex.prototype.setLocation = function(x, y) {};

/**
 * @interface
 */
var FlashTimeline = function() {};
/**
 * @type {number}
 */
FlashTimeline.prototype.currentFrame;

/**
 * @type {number}
 */
FlashTimeline.prototype.currentLayer;

/**
 * @type {number}
 */
FlashTimeline.prototype.frameCount;

/**
 * @type {number}
 */
FlashTimeline.prototype.layerCount;

/**
 * @type {Array}
 */
FlashTimeline.prototype.layers;

/**
 * @type {string}
 */
FlashTimeline.prototype.name;

/**
 * @type {FlashItem}
 */
FlashTimeline.prototype.libraryItem;

/**
 * @return {number}
 */
FlashTimeline.prototype.addMotionGuide = function() {};

/**
 * @param {string=} name
 * @param {string=} layerType
 * @param {boolean=} bAddAbove
 */
FlashTimeline.prototype.addNewLayer = function(name, layerType, bAddAbove) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.clearFrames = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.clearKeyframes = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.convertToBlankKeyframes = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.convertToKeyframes = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.copyFrames = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.copyLayers = function(startFrameIndex, endFrameIndex) {};

/**
 */
FlashTimeline.prototype.copyMotion = function() {};

/**
 */
FlashTimeline.prototype.copyMotionAsAS3 = function() {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.createMotionObject = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.createMotionTween = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.cutFrames = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number=} startLayerIndex
 * @param {number=} endLayerIndex
 */
FlashTimeline.prototype.cutLayers = function(startLayerIndex, endLayerIndex) {};

/**
 * @param {number} index
 */
FlashTimeline.prototype.deleteLayer = function(index) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.duplicateLayers = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {boolean} bExpand
 * @param {boolean=} bRecurseNestedParents
 * @param {number=} index
 */
FlashTimeline.prototype.expandFolder = function(bExpand, bRecurseNestedParents, index) {};

/**
 * @param {string} name
 * @return {Array}
 */
FlashTimeline.prototype.findLayerIndex = function(name) {};

/**
 * @param {string} property
 * @param {number=} startframeIndex
 * @param {number=} endFrameIndex
 * @return {Object}
 */
FlashTimeline.prototype.getFrameProperty = function(property, startframeIndex, endFrameIndex) {};

/**
 * @return {string}
 */
FlashTimeline.prototype.getGuidelines = function() {};

/**
 * @param {string} property
 * @return {Object}
 */
FlashTimeline.prototype.getLayerProperty = function(property) {};

/**
 * @return {Array}
 */
FlashTimeline.prototype.getSelectedFrames = function() {};

/**
 * @return {Array}
 */
FlashTimeline.prototype.getSelectedLayers = function() {};

/**
 * @param {number=} frameNumIndex
 */
FlashTimeline.prototype.insertBlankKeyframe = function(frameNumIndex) {};

/**
 * @param {number=} numFrames
 * @param {boolean=} bAllLayers
 * @param {number=} frameNumIndex
 */
FlashTimeline.prototype.insertFrames = function(numFrames, bAllLayers, frameNumIndex) {};

/**
 * @param {number=} frameNumIndex
 */
FlashTimeline.prototype.insertKeyframe = function(frameNumIndex) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.pasteFrames = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number} layerIndex
 * @return {number}
 */
FlashTimeline.prototype.pasteLayers = function(layerIndex) {};

/**
 */
FlashTimeline.prototype.pasteMotion = function() {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.removeFrames = function(startFrameIndex, endFrameIndex) {};

/**
 * @param {number} startFrame
 * @param {number} endFrame
 */
FlashTimeline.prototype.removeMotionObject = function(startFrame, endFrame) {};

/**
 * @param {number} layerToMove
 * @param {number} layerToPutItBy
 * @param {boolean=} bAddBefore
 */
FlashTimeline.prototype.reorderLayer = function(layerToMove, layerToPutItBy, bAddBefore) {};

/**
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.reverseFrames = function(startFrameIndex, endFrameIndex) {};

/**
 */
FlashTimeline.prototype.selectAllFrames = function() {};

/**
 * @param {string} property
 * @param {Object} value
 * @param {number=} startFrameIndex
 * @param {number=} endFrameIndex
 */
FlashTimeline.prototype.setFrameProperty = function(property, value, startFrameIndex, endFrameIndex) {};

/**
 * @param {string} xmlString
 * @return {boolean}
 */
FlashTimeline.prototype.setGuidelines = function(xmlString) {};

/**
 * @param {string} property
 * @param {Object} value
 * @param {string=} layersToChange
 */
FlashTimeline.prototype.setLayerProperty = function(property, value, layersToChange) {};

/**
 * @param {Object} startFrameIndexOrSelectionList
 * @param {Object=} endFrameIndexOrBReplaceCurrentSelection
 * @param {boolean=} bReplaceCurrentSelection
 */
FlashTimeline.prototype.setSelectedFrames = function(startFrameIndexOrSelectionList, endFrameIndexOrBReplaceCurrentSelection, bReplaceCurrentSelection) {};

/**
 * @param {number} index
 * @param {boolean=} bReplaceCurrentSelection
 */
FlashTimeline.prototype.setSelectedLayers = function(index, bReplaceCurrentSelection) {};

/**
 * @param {number} layer
 */
FlashTimeline.prototype.showLayerMasking = function(layer) {};

/**
 */
FlashTimeline.prototype.startPlayback = function() {};

/**
 */
FlashTimeline.prototype.stopPlayback = function() {};

/**
 * @interface
 */
var FlashPath = function() {};
/**
 * @type {void}
 */
FlashPath.prototype.void;

/**
 * @type {number}
 */
FlashPath.prototype.nPts;

/**
 * @param {number} xAnchor
 * @param {number} yAnchor
 * @param {number} x2
 * @param {number} y2
 * @param {number} x3
 * @param {number} y3
 * @param {number} x4
 * @param {number} y4
 */
FlashPath.prototype.addCubicCurve = function(xAnchor, yAnchor, x2, y2, x3, y3, x4, y4) {};

/**
 * @param {number} xAnchor
 * @param {number} yAnchor
 * @param {number} x2
 * @param {number} y2
 * @param {number} x3
 * @param {number} y3
 */
FlashPath.prototype.addCurve = function(xAnchor, yAnchor, x2, y2, x3, y3) {};

/**
 * @param {number} x
 * @param {number} y
 */
FlashPath.prototype.addPoint = function(x, y) {};

/**
 */
FlashPath.prototype.clear = function() {};

/**
 */
FlashPath.prototype.close = function() {};

/**
 * @param {boolean=} bSupressFill
 * @param {boolean=} bSupressStroke
 */
FlashPath.prototype.makeShape = function(bSupressFill, bSupressStroke) {};

/**
 */
FlashPath.prototype.newContour = function() {};

/**
 * @interface
 */
var FlashDrawingLayer = function() {};
/**
 * @param {boolean=} persistentDraw
 */
FlashDrawingLayer.prototype.beginDraw = function(persistentDraw) {};

/**
 */
FlashDrawingLayer.prototype.beginFrame = function() {};

/**
 * @param {number} x1Ctrl
 * @param {number} y1Ctrl
 * @param {number} x2Ctl
 * @param {number} y2Ctl
 * @param {number} xEnd
 * @param {number} yEnd
 */
FlashDrawingLayer.prototype.cubicCurveTo = function(x1Ctrl, y1Ctrl, x2Ctl, y2Ctl, xEnd, yEnd) {};

/**
 * @param {number} xCtl
 * @param {number} yCtl
 * @param {number} xEnd
 * @param {number} yEnd
 */
FlashDrawingLayer.prototype.curveTo = function(xCtl, yCtl, xEnd, yEnd) {};

/**
 * @param {Object} path
 */
FlashDrawingLayer.prototype.drawPath = function(path) {};

/**
 */
FlashDrawingLayer.prototype.endDraw = function() {};

/**
 */
FlashDrawingLayer.prototype.endFrame = function() {};

/**
 * @param {number} x
 * @param {number} y
 */
FlashDrawingLayer.prototype.lineTo = function(x, y) {};

/**
 * @param {number} x
 * @param {number} y
 */
FlashDrawingLayer.prototype.moveTo = function(x, y) {};

/**
 */
FlashDrawingLayer.prototype.newPath = function() {};

/**
 * @param {Object} color
 */
FlashDrawingLayer.prototype.setColor = function(color) {};

/**
 */
FlashDrawingLayer.prototype.setFill = function() {};

/**
 */
FlashDrawingLayer.prototype.setStroke = function() {};

/**
 * @interface
 */
var FlashXMLUI = function() {};
/**
 */
FlashXMLUI.prototype.accept = function() {};

/**
 */
FlashXMLUI.prototype.cancel = function() {};

/**
 */
FlashXMLUI.prototype.get = function() {};

/**
 */
FlashXMLUI.prototype.getControlItemElement = function() {};

/**
 */
FlashXMLUI.prototype.getEnabled = function() {};

/**
 */
FlashXMLUI.prototype.getVisible = function() {};

/**
 */
FlashXMLUI.prototype.set = function() {};

/**
 */
FlashXMLUI.prototype.setControItemElement = function() {};

/**
 */
FlashXMLUI.prototype.setControItemElements = function() {};

/**
 */
FlashXMLUI.prototype.setEnabled = function() {};

/**
 */
FlashXMLUI.prototype.setVisible = function() {};

/**
 * @interface
 */
var FlashActionsPanel = function() {};
/**
 */
FlashActionsPanel.prototype.getClassForObject = function() {};

/**
 */
FlashActionsPanel.prototype.getScriptAssistMode = function() {};

/**
 */
FlashActionsPanel.prototype.getSelectedText = function() {};

/**
 */
FlashActionsPanel.prototype.getText = function() {};

/**
 */
FlashActionsPanel.prototype.hasSelection = function() {};

/**
 */
FlashActionsPanel.prototype.replaceSelectedText = function() {};

/**
 */
FlashActionsPanel.prototype.setScriptAssistMode = function() {};

/**
 */
FlashActionsPanel.prototype.setSelection = function() {};

/**
 */
FlashActionsPanel.prototype.setText = function() {};

/**
 * @interface
 */
var FlashCompilerErrors = function() {};
/**
 */
FlashCompilerErrors.prototype.clear = function() {};

/**
 */
FlashCompilerErrors.prototype.save = function() {};

/**
 * @interface
 */
var FlashComponentsPanel = function() {};
/**
 */
FlashComponentsPanel.prototype.addItemToDocument = function() {};

/**
 */
FlashComponentsPanel.prototype.reload = function() {};

/**
 * @interface
 */
var FlashPresetPanel = function() {};
/**
 */
FlashPresetPanel.prototype.addNewItem = function() {};

/**
 */
FlashPresetPanel.prototype.applyPreset = function() {};

/**
 */
FlashPresetPanel.prototype.deleteFolder = function() {};

/**
 */
FlashPresetPanel.prototype.deleteItem = function() {};

/**
 */
FlashPresetPanel.prototype.expandFolder = function() {};

/**
 */
FlashPresetPanel.prototype.exportItem = function() {};

/**
 */
FlashPresetPanel.prototype.findItemIndex = function() {};

/**
 */
FlashPresetPanel.prototype.getSelectedItems = function() {};

/**
 */
FlashPresetPanel.prototype.importItem = function() {};

/**
 */
FlashPresetPanel.prototype.moveToFolder = function() {};

/**
 */
FlashPresetPanel.prototype.newFolder = function() {};

/**
 */
FlashPresetPanel.prototype.renameItem = function() {};

/**
 */
FlashPresetPanel.prototype.selectItem = function() {};

/**
 * @interface
 */
var FlashSwfPanel = function() {};
/**
 * @type {void}
 */
FlashSwfPanel.prototype.name;

/**
 * @type {void}
 */
FlashSwfPanel.prototype.path;

/**
 */
FlashSwfPanel.prototype.call = function() {};

/**
 */
FlashSwfPanel.prototype.setFocus = function() {};

/**
 * @interface
 */
var FlashTools = function() {};
/**
 * @type {void}
 */
FlashTools.prototype.activeTool;

/**
 * @type {void}
 */
FlashTools.prototype.altIsDown;

/**
 * @type {void}
 */
FlashTools.prototype.ctlIsDown;

/**
 * @type {void}
 */
FlashTools.prototype.mouseIsDown;

/**
 * @type {void}
 */
FlashTools.prototype.penDownLoc;

/**
 * @type {void}
 */
FlashTools.prototype.penLoc;

/**
 * @type {void}
 */
FlashTools.prototype.shiftIsDown;

/**
 * @type {void}
 */
FlashTools.prototype.toolObjs;

/**
 */
FlashTools.prototype.constraintPoint = function() {};

/**
 */
FlashTools.prototype.getKeyDown = function() {};

/**
 */
FlashTools.prototype.setCreatingBbox = function() {};

/**
 */
FlashTools.prototype.setCursor = function() {};

/**
 */
FlashTools.prototype.snapPoint = function() {};

/**
 * @constructor
 */
var SpriteSheetExporter = function() {}

/**
 * @type {string}
 */
SpriteSheetExporter.prototype.algorithm;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.allowRotate;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.allowTrimming;

/**
 * @type {string}
 */
SpriteSheetExporter.prototype.app;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.autoSize;

/**
 * @type {number}
 */
SpriteSheetExporter.prototype.borderPadding;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.canBorderPad;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.canRotate;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.canTrim;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.canShapePad;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.canStackDuplicateFrames;

/**
 * @type {string}
 */
SpriteSheetExporter.prototype.format;

/**
 * @type {string}
 */
SpriteSheetExporter.prototype.image;

/**
 * @type {string}
 */
SpriteSheetExporter.prototype.layoutFormat;

/**
 * @type {number}
 */
SpriteSheetExporter.prototype.maxSheetHeight;

/**
 * @type {number}
 */
SpriteSheetExporter.prototype.maxSheetWidth;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.overflowed;

/**
 * @type {number}
 */
SpriteSheetExporter.prototype.shapePadding;

/**
 * @type {number}
 */
SpriteSheetExporter.prototype.sheetHeight;

/**
 * @type {number}
 */
SpriteSheetExporter.prototype.sheetWidth;

/**
 * @type {boolean}
 */
SpriteSheetExporter.prototype.stackDuplicateFrames;

/**
 * @type {string}
 */
SpriteSheetExporter.prototype.version;

/**
 * @param {Object} item
 */
SpriteSheetExporter.prototype.addBitmap = function(item) {};

/**
 * @param {Object} item
 * @param {string=} name
 * @param {number=} beginFrame
 * @param {number=} endFrame
 */
SpriteSheetExporter.prototype.addSymbol = function(item, name, beginFrame, endFrame) {};

/**
 */
SpriteSheetExporter.prototype.beginExport = function() {};

/**
 */
SpriteSheetExporter.prototype.changeSymbol = function() {};

/**
 * @param {string} fileURL
 * @param {Object} option
 * @param {boolean=} writeMetaData
 * @return {string}
 */
SpriteSheetExporter.prototype.exportSpriteSheet = function(fileURL, option, writeMetaData) {};

/**
 */
SpriteSheetExporter.prototype.removeBitmap = function() {};

/**
 */
SpriteSheetExporter.prototype.removeSymbol = function() {};

/**
 * @interface
 */
var FlashFL = function() {};
/**
 * @type {FlashActionsPanel}
 */
FlashFL.prototype.actionsPanel;

/**
 * @type {string}
 */
FlashFL.prototype.as3PackagePaths;

/**
 * @type {FlashCompilerErrors}
 */
FlashFL.prototype.compilerErrors;

/**
 * @type {FlashComponentsPanel}
 */
FlashFL.prototype.componentsPanel;

/**
 * @type {string}
 */
FlashFL.prototype.configDirectory;

/**
 * @type {string}
 */
FlashFL.prototype.configURI;

/**
 * @type {boolean}
 */
FlashFL.prototype.contactSensitiveSelection;

/**
 * @type {Array}
 */
FlashFL.prototype.createNewDocList;

/**
 * @type {Array}
 */
FlashFL.prototype.createNewDocListType;

/**
 * @type {Array}
 */
FlashFL.prototype.createNewTemplateList;

/**
 * @type {Array}
 */
FlashFL.prototype.documents;

/**
 * @type {FlashDrawingLayer}
 */
FlashFL.prototype.drawingLayer;

/**
 * @type {string}
 */
FlashFL.prototype.externalLibraryPath;

/**
 * @type {string}
 */
FlashFL.prototype.flexSDKPath;

/**
 * @type {Array}
 */
FlashFL.prototype.installedPlayers;

/**
 * @type {string}
 */
FlashFL.prototype.languageCode;

/**
 * @type {string}
 */
FlashFL.prototype.libraryPath;

/**
 * @type {FlashMath}
 */
FlashFL.prototype.Math;

/**
 * @type {Array}
 */
FlashFL.prototype.mruRecentFileList;

/**
 * @type {Array}
 */
FlashFL.prototype.mruRecentFileListType;

/**
 * @type {Array}
 */
FlashFL.prototype.packagePaths;

/**
 * @type {number}
 */
FlashFL.prototype.publishCacheDiskSizeMax;

/**
 * @type {boolean}
 */
FlashFL.prototype.publishCacheEnabled;

/**
 * @type {number}
 */
FlashFL.prototype.publishCacheMemoryEntrySizeLimit;

/**
 * @type {number}
 */
FlashFL.prototype.publishCacheMemorySizeMax;

/**
 * @type {number}
 */
FlashFL.prototype.objectDrawingMode;

/**
 * @type {FlashOutputPanel}
 */
FlashFL.prototype.outputPanel;

/**
 * @type {FlashPresetPanel}
 */
FlashFL.prototype.presetPanel;

/**
 * @type {string}
 */
FlashFL.prototype.scriptURI;

/**
 * @type {string}
 */
FlashFL.prototype.sourcePath;

/**
 * @type {Array}
 */
FlashFL.prototype.swfPanels;

/**
 * @type {Array}
 */
FlashFL.prototype.tools;

/**
 * @type {string}
 */
FlashFL.prototype.version;

/**
 * @type {FlashXMLUI}
 */
FlashFL.prototype.xmlui;

/**
 * @param {Object} eventType
 * @param {Object} callbackFunction
 */
FlashFL.prototype.addEventListener = function(eventType, callbackFunction) {};

/**
 * @param {Object} browseType
 * @param {Object=} title
 * @param {Object=} previewArea
 * @param {Object=} fileFilter
 */
FlashFL.prototype.browseForFileURL = function(browseType, title, previewArea, fileFilter) {};

/**
 * @param {string} description
 */
FlashFL.prototype.browseForFolderURL = function(description) {};

/**
 */
FlashFL.prototype.clearPublishCache = function() {};

/**
 * @param {string} string
 */
FlashFL.prototype.clipCopyString = function(string) {};

/**
 * @param {boolean=} bPromptToSave
 */
FlashFL.prototype.closeAll = function(bPromptToSave) {};

/**
 * @return {boolean}
 */
FlashFL.prototype.closeAllPlayerDocuments = function() {};

/**
 * @param {Object} documentObject
 * @param {boolean=} bPromptToSaveChanges
 */
FlashFL.prototype.closeDocument = function(documentObject, bPromptToSaveChanges) {};

/**
 * @param {string=} document
 * @return {FlashDocument}
 */
FlashFL.prototype.createDocument = function(document) {};

/**
 * @param {string} ucfURI
 * @param {string} profileName
 * @return {string}
 */
FlashFL.prototype.exportPublishProfileString = function(ucfURI, profileName) {};

/**
 * @param {string} fileURI
 * @return {boolean}
 */
FlashFL.prototype.fileExists = function(fileURI) {};

/**
 * @param {number} id
 * @return {FlashDocument}
 */
FlashFL.prototype.findDocumentDOM = function(id) {};

/**
 * @param {string} name
 * @return {Array}
 */
FlashFL.prototype.findDocumentIndex = function(name) {};

/**
 * @param {string} instanceName
 * @param {Object} document
 * @return {Array}
 */
FlashFL.prototype.findObjectInDocByName = function(instanceName, document) {};

/**
 * @param {string} elementType
 * @param {Object} document
 * @return {Array}
 */
FlashFL.prototype.findObjectInDocByType = function(elementType, document) {};

/**
 * @param {number} memType
 */
FlashFL.prototype.getAppMemoryInfo = function(memType) {};

/**
 * @return {FlashDocument}
 */
FlashFL.prototype.getDocumentDOM = function() {};

/**
 */
FlashFL.prototype.getSwfPanel = function() {};

/**
 */
FlashFL.prototype.isFontInstalled = function() {};

/**
 * @param {string} URI
 * @param {boolean=} returnMBCS
 * @return {string}
 */
FlashFL.prototype.mapPlayerURL = function(URI, returnMBCS) {};

/**
 * @param {string} fileURI
 * @return {FlashDocument}
 */
FlashFL.prototype.openDocument = function(fileURI) {};

/**
 * @param {string} fileURI
 * @param {string=} createExtension
 * @param {string=} className
 */
FlashFL.prototype.openScript = function(fileURI, createExtension, className) {};

/**
 * @param {boolean=} bPromptIfNeeded
 */
FlashFL.prototype.quit = function(bPromptIfNeeded) {};

/**
 */
FlashFL.prototype.reloadTools = function() {};

/**
 * @param {string} eventType
 * @return {boolean}
 */
FlashFL.prototype.removeEventListener = function(eventType) {};

/**
 */
FlashFL.prototype.resetAS3PackagePaths = function() {};

/**
 */
FlashFL.prototype.resetPackagePaths = function() {};

/**
 * @param {Object} document
 */
FlashFL.prototype.revertDocument = function(document) {};

/**
 * @param {string} fileURI
 * @param {Function=} funcName
 * @param {Array=} args
 * @return {Object}
 */
FlashFL.prototype.runScript = function(fileURI, funcName, args) {};

/**
 */
FlashFL.prototype.saveAll = function() {};

/**
 * @param {Object} document
 * @param {string=} fileURI
 * @return {boolean}
 */
FlashFL.prototype.saveDocument = function(document, fileURI) {};

/**
 * @param {Object} document
 * @return {boolean}
 */
FlashFL.prototype.saveDocumentAs = function(document) {};

/**
 * @param {Object} elementObject
 * @param {boolean} editMode
 * @return {boolean}
 */
FlashFL.prototype.selectElement = function(elementObject, editMode) {};

/**
 * @param {string} toolName
 */
FlashFL.prototype.selectTool = function(toolName) {};

/**
 * @param {Object} document
 * @param {boolean=} bActivateFrame
 */
FlashFL.prototype.selectActiveWindow = function(document, bActivateFrame) {};

/**
 * @param {boolean} show
 */
FlashFL.prototype.showIdleMessage = function(show) {};

/**
 */
FlashFL.prototype.toggleBreakpoint = function() {};

/**
 * @param {Object} message
 */
FlashFL.prototype.trace = function(message) {};

/**
 * @type {FlashFL}
 */
var fl;

/**
 * @type {FlashFLfile}
 */
var FLfile;

