// generated by dts2as from NextGenActionScript.com
package 
{
public interface _FlashBitmap
{
function get width():void;
function set width(value:void):void;
function get height():void;
function set height(value:void):void;
function get depth():void;
function set depth(value:void):void;
function get bits():void;
function set bits(value:void):void;
}
}