// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashXMLUI
{
function accept():void;
function cancel():void;
function get():void;
function getControlItemElement():void;
function getEnabled():void;
function getVisible():void;
function set():void;
function setControItemElement():void;
function setControItemElements():void;
function setEnabled():void;
function setVisible():void;
}
}