// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashVideoItem
{
function get fileLastModifiedDate():String;
function set fileLastModifiedDate(value:String):void;
function get sourceFileExists():Boolean;
function set sourceFileExists(value:Boolean):void;
function get sourceFileIsCurrent():Boolean;
function set sourceFileIsCurrent(value:Boolean):void;
function get sourceFilePath():String;
function set sourceFilePath(value:String):void;
function get videoType():String;
function set videoType(value:String):void;
function exportToFLV(fileURI:String):Boolean;
}
}