// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashItem extends FlashSymbolItem, FlashFolderItem, FlashFontItem, FlashSoundItem, FlashVideoItem, FlashBitmapItem, FlashBitmapItem
{
function get itemType():String;
function set itemType(value:String):void;
function get linkageBaseClass():String;
function set linkageBaseClass(value:String):void;
function get linkageClassName():String;
function set linkageClassName(value:String):void;
function get linkageExportForAS():Boolean;
function set linkageExportForAS(value:Boolean):void;
function get linkageExportForRS():Boolean;
function set linkageExportForRS(value:Boolean):void;
function get linkageExportInFirstFrame():Boolean;
function set linkageExportInFirstFrame(value:Boolean):void;
function get linkageIdentifier():String;
function set linkageIdentifier(value:String):void;
function get linkageImportForRS():Boolean;
function set linkageImportForRS(value:Boolean):void;
function get linkageURL():String;
function set linkageURL(value:String):void;
function get name():String;
function set name(value:String):void;
function addData(name:String, type:String, data:Object):void;
function getData(name:String):Object;
function hasData(name:String):Boolean;
function removeData(name:String):void;
}
}