// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashFill
{
function get bitmapIsClipped():Boolean;
function set bitmapIsClipped(value:Boolean):void;
function get bitmapPath():String;
function set bitmapPath(value:String):void;
function get color():Object;
function set color(value:Object):void;
function get colorArray():Array;
function set colorArray(value:Array):void;
function get focalPoint():Number;
function set focalPoint(value:Number):void;
function get linearRGB():Boolean;
function set linearRGB(value:Boolean):void;
function get matrix():FlashMatrix;
function set matrix(value:FlashMatrix):void;
function get overflow():String;
function set overflow(value:String):void;
function get posArray():Array;
function set posArray(value:Array):void;
function get style():String;
function set style(value:String):void;
}
}