// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashStroke
{
function get breakAtCorners():Boolean;
function set breakAtCorners(value:Boolean):void;
function get capType():String;
function set capType(value:String):void;
function get color():Object;
function set color(value:Object):void;
function get curve():String;
function set curve(value:String):void;
function get dash1():Number;
function set dash1(value:Number):void;
function get dash2():Number;
function set dash2(value:Number):void;
function get density():String;
function set density(value:String):void;
function get dotSize():String;
function set dotSize(value:String):void;
function get dotSpace():Number;
function set dotSpace(value:Number):void;
function get hatchThickness():String;
function set hatchThickness(value:String):void;
function get jiggle():String;
function set jiggle(value:String):void;
function get joinType():String;
function set joinType(value:String):void;
function get length():String;
function set length(value:String):void;
function get miterLimit():Number;
function set miterLimit(value:Number):void;
function get pattern():String;
function set pattern(value:String):void;
function get rotate():String;
function set rotate(value:String):void;
function get scaleType():String;
function set scaleType(value:String):void;
function get shapeFill():FlashFill;
function set shapeFill(value:FlashFill):void;
function get space():String;
function set space(value:String):void;
function get strokeHinting():Boolean;
function set strokeHinting(value:Boolean):void;
function get style():String;
function set style(value:String):void;
function get thickness():Number;
function set thickness(value:Number):void;
function get variation():String;
function set variation(value:String):void;
function get waveHeight():String;
function set waveHeight(value:String):void;
function get waveLength():String;
function set waveLength(value:String):void;
}
}