// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashTextAttrs extends FlashText
{
function get aliasText():Boolean;
function set aliasText(value:Boolean):void;
function get alignment():String;
function set alignment(value:String):void;
function get autoKern():Boolean;
function set autoKern(value:Boolean):void;
function get bold():Boolean;
function set bold(value:Boolean):void;
function get characterPosition():String;
function set characterPosition(value:String):void;
function get characterSpacing():Number;
function set characterSpacing(value:Number):void;
function get face():String;
function set face(value:String):void;
function get fillColor():Object;
function set fillColor(value:Object):void;
function get indent():Number;
function set indent(value:Number):void;
function get italic():Boolean;
function set italic(value:Boolean):void;
function get leftMargin():Number;
function set leftMargin(value:Number):void;
function get letterSpacing():Number;
function set letterSpacing(value:Number):void;
function get lineSpacing():Number;
function set lineSpacing(value:Number):void;
function get rightMargin():Number;
function set rightMargin(value:Number):void;
function get rotation():Boolean;
function set rotation(value:Boolean):void;
function get size():Number;
function set size(value:Number):void;
function get target():String;
function set target(value:String):void;
function get url():String;
function set url(value:String):void;
}
}