// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashContour
{
function get fill():FlashFill;
function set fill(value:FlashFill):void;
function get interior():Boolean;
function set interior(value:Boolean):void;
function get orientation():Number;
function set orientation(value:Number):void;
function getHalfEdge():FlashHalfEdge;
}
}