// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashPresetPanel
{
function addNewItem():void;
function applyPreset():void;
function deleteFolder():void;
function deleteItem():void;
function expandFolder():void;
function exportItem():void;
function findItemIndex():void;
function getSelectedItems():void;
function importItem():void;
function moveToFolder():void;
function newFolder():void;
function renameItem():void;
function selectItem():void;
}
}