// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashOval
{
function get closePath():Boolean;
function set closePath(value:Boolean):void;
function get endAngle():Number;
function set endAngle(value:Number):void;
function get innerRadius():Number;
function set innerRadius(value:Number):void;
function get startAngle():Number;
function set startAngle(value:Number):void;
}
}