// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashActionsPanel
{
function getClassForObject():void;
function getScriptAssistMode():void;
function getSelectedText():void;
function getText():void;
function hasSelection():void;
function replaceSelectedText():void;
function setScriptAssistMode():void;
function setSelection():void;
function setText():void;
}
}