// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashLibrary
{
function get items():Array;
function set items(value:Array):void;
function addItemToDocument(position:Object, namePath:String = undefined):Boolean;
function addNewItem(type:String, namePath:String = undefined):Boolean;
function deleteItem(namePath:String = undefined):Boolean;
function duplicateItem(namePath:String):Boolean;
function editItem(namePath:String = undefined):Boolean;
function expandFolder(bExpand:Boolean, bRecurseNestedParents:Boolean = undefined, namePath:String = undefined):Boolean;
function findItemIndex(namePath:String):Number;
function getItemProperty(property:String):String;
function getItemType(namePath:String = undefined):String;
function getSelectedItems():Array;
function importEmbeddedSWF(linkageName:String, swfData:Array, libName:String = undefined):void;
function itemExists(namePath:String):Boolean;
function moveToFolder(folderPath:String, itemToMove:String = undefined, bReplace:Boolean = undefined):Boolean;
function newFolder(folderPath:String = undefined):Boolean;
function renameItem(name:String):Boolean;
function selectAll(bSelectAll:Boolean = undefined):void;
function selectItem(namePath:String, bReplaceCurrentSelection:Boolean = undefined, bSelect:Boolean = undefined):Boolean;
function selectNone():void;
function setItemProperty(property:String, value:Object):void;
function updateItem(namePath:String):Boolean;
}
}