// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashBitmapInstance
{
function get hPixels():Number;
function set hPixels(value:Number):void;
function get vPixels():Number;
function set vPixels(value:Number):void;
function getBits():_FlashBitmap;
function setBits(bitmap:Object):void;
}
}