// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashFrame
{
function get actionScript():void;
function set actionScript(value:void):void;
function get duration():void;
function set duration(value:void):void;
function get elements():Array;
function set elements(value:Array):void;
function get hasCustomEase():void;
function set hasCustomEase(value:void):void;
function get labelType():void;
function set labelType(value:void):void;
function get motionTweenOrientToPath():void;
function set motionTweenOrientToPath(value:void):void;
function get motionTweenRotate():void;
function set motionTweenRotate(value:void):void;
function get motionTweenRotateTimes():void;
function set motionTweenRotateTimes(value:void):void;
function get motionTweenScale():void;
function set motionTweenScale(value:void):void;
function get motionTweenSnap():void;
function set motionTweenSnap(value:void):void;
function get motionTweenSync():void;
function set motionTweenSync(value:void):void;
function get name():void;
function set name(value:void):void;
function get shapeTweenBlend():void;
function set shapeTweenBlend(value:void):void;
function get soundEffect():void;
function set soundEffect(value:void):void;
function get soundLibraryItem():FlashSoundItem;
function set soundLibraryItem(value:FlashSoundItem):void;
function get soundLoop():void;
function set soundLoop(value:void):void;
function get soundLoopMode():void;
function set soundLoopMode(value:void):void;
function get soundName():void;
function set soundName(value:void):void;
function get soundSync():void;
function set soundSync(value:void):void;
function get startFrame():void;
function set startFrame(value:void):void;
function get tweenEasing():void;
function set tweenEasing(value:void):void;
function get tweenType():void;
function set tweenType(value:void):void;
function get useSingleEaseCurve():void;
function set useSingleEaseCurve(value:void):void;
function getCustomEase():void;
function setCustomEase():void;
}
}