// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashFilter
{
function get angle():Number;
function set angle(value:Number):void;
function get blurX():Number;
function set blurX(value:Number):void;
function get blurY():Number;
function set blurY(value:Number):void;
function get brightness():Number;
function set brightness(value:Number):void;
function get color():Object;
function set color(value:Object):void;
function get contrast():Number;
function set contrast(value:Number):void;
function get distance():Number;
function set distance(value:Number):void;
function get enabled():Boolean;
function set enabled(value:Boolean):void;
function get hideObject():Boolean;
function set hideObject(value:Boolean):void;
function get highlightColor():Object;
function set highlightColor(value:Object):void;
function get hue():Number;
function set hue(value:Number):void;
function get inner():Boolean;
function set inner(value:Boolean):void;
function get knockout():Boolean;
function set knockout(value:Boolean):void;
function get name():String;
function set name(value:String):void;
function get quality():String;
function set quality(value:String):void;
function get saturation():Number;
function set saturation(value:Number):void;
function get shadowColor():Object;
function set shadowColor(value:Object):void;
function get strength():Number;
function set strength(value:Number):void;
function get type():String;
function set type(value:String):void;
}
}