// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashMath
{
function concatMatrix(mat1:Object, mat2:Object):FlashMatrix;
function invertMatrix(mat:Object):FlashMatrix;
function pointDistance(pt1:Object, pt2:Object):Number;
}
}