// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashOutputPanel
{
function clear():void;
function save(fileURI:String, bAppendToFile:Boolean = undefined, bUseSystemEncoding:Boolean = undefined):void;
function trace(message:String):void;
}
}