// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashFLfile
{
function copy(fileURI:String, copyURI:String):Boolean;
function createFolder(folderURI:String):Boolean;
function exists(fileURI:String):Boolean;
function getAttributes(fileOrFolderURI:String):String;
function getCreationDate(fileOrFolderURI:String):String;
function getCreationDateObj(fileOrFolderURI:String):Date;
function getModificationDate(fileOrFolderURI:String):String;
function getModificationDateObj(fileOrFolderURI:String):Date;
function getSize(fileURI:String):Number;
function listFolder(folderURI:String, filesOrDirectories:Boolean = undefined):Array;
function platformPathToURI(fileName:String):String;
function read(fileOrFolderURI:String):String;
function remove(fileOrFolderURI:String):Boolean;
function setAttributes(fileURI:String, strAttrs:String):Boolean;
function uriToPlatformPath(fileURI:String):String;
function write(fileURI:String, textToWrite:String, strAppendMode:String = undefined):Boolean;
}
}