// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashElement extends FlashInstance, FlashBitmapInstance, FlashCompiledClipInstance, FlashSymbolInstance, FlashComponentInstance, FlashShape
{
function get depth():Number;
function set depth(value:Number):void;
function get elementType():String;
function set elementType(value:String):void;
function get height():Number;
function set height(value:Number):void;
function get layer():FlashLayer;
function set layer(value:FlashLayer):void;
function get left():Number;
function set left(value:Number):void;
function get locked():Boolean;
function set locked(value:Boolean):void;
function get matrix():FlashMatrix;
function set matrix(value:FlashMatrix):void;
function get name():String;
function set name(value:String):void;
function get rotation():Number;
function set rotation(value:Number):void;
function get scaleX():Number;
function set scaleX(value:Number):void;
function get scaleY():Number;
function set scaleY(value:Number):void;
function get selected():Boolean;
function set selected(value:Boolean):void;
function get skewX():Number;
function set skewX(value:Number):void;
function get skewY():Number;
function set skewY(value:Number):void;
function get top():Number;
function set top(value:Number):void;
function get transformX():Number;
function set transformX(value:Number):void;
function get transformY():Number;
function set transformY(value:Number):void;
function get width():Number;
function set width(value:Number):void;
function get x():Number;
function set x(value:Number):void;
function get y():Number;
function set y(value:Number):void;
function getPersistentData(name:String):Object;
function getTransformationPoint():FlashPoint;
function hasPersistentData(name:String):Boolean;
function removePersistentData(name:String):void;
function setPersistentData(name:String, type:String, value:Object):void;
function setTransformationPoint(transformationPoint:Object):void;
}
}