// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashSoundItem
{
function get bitRate():String;
function set bitRate(value:String):void;
function get bits():String;
function set bits(value:String):void;
function get compressionType():String;
function set compressionType(value:String):void;
function get convertStereoToMono():Boolean;
function set convertStereoToMono(value:Boolean):void;
function get fileLastModifiedDate():String;
function set fileLastModifiedDate(value:String):void;
function get originalCompressionType():String;
function set originalCompressionType(value:String):void;
function get quality():String;
function set quality(value:String):void;
function get sampleRate():String;
function set sampleRate(value:String):void;
function get sourceFileExists():Boolean;
function set sourceFileExists(value:Boolean):void;
function exportToFile(fileURI:String):Boolean;
}
}