// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashFontItem
{
function get bitmap():Boolean;
function set bitmap(value:Boolean):void;
function get bold():Boolean;
function set bold(value:Boolean):void;
function get embeddedCharacters():String;
function set embeddedCharacters(value:String):void;
function get embedRanges():String;
function set embedRanges(value:String):void;
function get embedVariantGlyphs():Boolean;
function set embedVariantGlyphs(value:Boolean):void;
function get font():String;
function set font(value:String):void;
function get isDefineFont4Symbol():Boolean;
function set isDefineFont4Symbol(value:Boolean):void;
function get italic():Boolean;
function set italic(value:Boolean):void;
function get size():Number;
function set size(value:Number):void;
}
}