// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashSymbolInstance
{
function get accName():String;
function set accName(value:String):void;
function get actionScript():String;
function set actionScript(value:String):void;
function get backgroundColor():String;
function set backgroundColor(value:String):void;
function get bitmapRenderMode():String;
function set bitmapRenderMode(value:String):void;
function get blendMode():String;
function set blendMode(value:String):void;
function get buttonTracking():String;
function set buttonTracking(value:String):void;
function get cacheAsBitmap():Boolean;
function set cacheAsBitmap(value:Boolean):void;
function get colorAlphaAmount():Number;
function set colorAlphaAmount(value:Number):void;
function get colorAlphaPercent():Number;
function set colorAlphaPercent(value:Number):void;
function get colorBlueAmount():Number;
function set colorBlueAmount(value:Number):void;
function get colorBluePercent():Number;
function set colorBluePercent(value:Number):void;
function get colorGreenAmount():Number;
function set colorGreenAmount(value:Number):void;
function get colorGreenPercent():Number;
function set colorGreenPercent(value:Number):void;
function get colorMode():String;
function set colorMode(value:String):void;
function get colorRedAmount():Number;
function set colorRedAmount(value:Number):void;
function get colorRedPercent():Number;
function set colorRedPercent(value:Number):void;
function get description():String;
function set description(value:String):void;
function get filters():Array;
function set filters(value:Array):void;
function get firstFrame():Number;
function set firstFrame(value:Number):void;
function get forceSimple():Boolean;
function set forceSimple(value:Boolean):void;
function get loop():String;
function set loop(value:String):void;
function get shortcut():String;
function set shortcut(value:String):void;
function get silent():Boolean;
function set silent(value:Boolean):void;
function get symbolType():String;
function set symbolType(value:String):void;
function get tabIndex():Number;
function set tabIndex(value:Number):void;
function get useBackgroundColor():Boolean;
function set useBackgroundColor(value:Boolean):void;
function get visible():Boolean;
function set visible(value:Boolean):void;
}
}