// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashVertex
{
function get x():Number;
function set x(value:Number):void;
function get y():Number;
function set y(value:Number):void;
function getHalfEdge():FlashHalfEdge;
function setLocation(x:Number, y:Number):void;
}
}