// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashHalfEdge
{
function get id():Number;
function set id(value:Number):void;
function get index():Number;
function set index(value:Number):void;
function getEdge():FlashEdge;
function getNext():FlashHalfEdge;
function getOppositeHalfEdge():FlashHalfEdge;
function getPrev():FlashHalfEdge;
function getVertex():FlashVertex;
}
}