// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashSymbolItem
{
function get scalingGrid():Boolean;
function set scalingGrid(value:Boolean):void;
function get scalingGridRect():FlashRectangle;
function set scalingGridRect(value:FlashRectangle):void;
function get sourceAutoUpdate():Boolean;
function set sourceAutoUpdate(value:Boolean):void;
function get sourceFilePath():String;
function set sourceFilePath(value:String):void;
function get sourceLibraryName():String;
function set sourceLibraryName(value:String):void;
function get symbolType():String;
function set symbolType(value:String):void;
function get timeline():FlashTimeline;
function set timeline(value:FlashTimeline):void;
function convertToCompiledClip():void;
function exportSWC(outputURI:String):void;
function exportSWF(outputURI:String):void;
}
}