// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashPoint
{
function get x():Number;
function set x(value:Number):void;
function get y():Number;
function set y(value:Number):void;
}
}