// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashPath
{
function get void():*;
function set void(value:*):void;
function get nPts():Number;
function set nPts(value:Number):void;
function addCubicCurve(xAnchor:Number, yAnchor:Number, x2:Number, y2:Number, x3:Number, y3:Number, x4:Number, y4:Number):*;
function addCurve(xAnchor:Number, yAnchor:Number, x2:Number, y2:Number, x3:Number, y3:Number):*;
function addPoint(x:Number, y:Number):*;
function clear():*;
function close():*;
function makeShape(bSupressFill:Boolean = undefined, bSupressStroke:Boolean = undefined):*;
function newContour():*;
}
}