// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashText
{
function get accName():String;
function set accName(value:String):void;
function get antiAliasSharpness():Number;
function set antiAliasSharpness(value:Number):void;
function get antiAliasThickness():Number;
function set antiAliasThickness(value:Number):void;
function get autoExpand():Boolean;
function set autoExpand(value:Boolean):void;
function get border():Boolean;
function set border(value:Boolean):void;
function get description():String;
function set description(value:String):void;
function get embeddedCharacters():String;
function set embeddedCharacters(value:String):void;
function getTextAttr():void;
function getTextString():void;
function setTextAttr():void;
function setTextString():void;
}
}