// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashSwfPanel
{
function get name():void;
function set name(value:void):void;
function get path():void;
function set path(value:void):void;
function call():void;
function setFocus():void;
}
}