// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashLayer
{
function get color():Object;
function set color(value:Object):void;
function get frameCount():Number;
function set frameCount(value:Number):void;
function get frames():Array;
function set frames(value:Array):void;
function get height():Number;
function set height(value:Number):void;
function get layerType():String;
function set layerType(value:String):void;
function get locked():Boolean;
function set locked(value:Boolean):void;
function get name():String;
function set name(value:String):void;
function get outline():Boolean;
function set outline(value:Boolean):void;
function get parentLayer():FlashLayer;
function set parentLayer(value:FlashLayer):void;
function get visible():Boolean;
function set visible(value:Boolean):void;
}
}