// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashTools
{
function get activeTool():void;
function set activeTool(value:void):void;
function get altIsDown():void;
function set altIsDown(value:void):void;
function get ctlIsDown():void;
function set ctlIsDown(value:void):void;
function get mouseIsDown():void;
function set mouseIsDown(value:void):void;
function get penDownLoc():void;
function set penDownLoc(value:void):void;
function get penLoc():void;
function set penLoc(value:void):void;
function get shiftIsDown():void;
function set shiftIsDown(value:void):void;
function get toolObjs():void;
function set toolObjs(value:void):void;
function constraintPoint():void;
function getKeyDown():void;
function setCreatingBbox():void;
function setCursor():void;
function snapPoint():void;
}
}