// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashBitmapItem
{
function get allowSmoothing():Boolean;
function set allowSmoothing(value:Boolean):void;
function get compressionType():String;
function set compressionType(value:String):void;
function get fileLastModifiedDate():String;
function set fileLastModifiedDate(value:String):void;
function get originalCompressionType():String;
function set originalCompressionType(value:String):void;
function get sourceFileExists():Boolean;
function set sourceFileExists(value:Boolean):void;
function get sourceFileIsCurrent():Boolean;
function set sourceFileIsCurrent(value:Boolean):void;
function get sourceFilePath():String;
function set sourceFilePath(value:String):void;
function get useDeblocking():Boolean;
function set useDeblocking(value:Boolean):void;
function get useImportedJPEGQuality():Boolean;
function set useImportedJPEGQuality(value:Boolean):void;
function exportToFile(fileURI:String):Boolean;
}
}