// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashCompiledClipInstance
{
function get accName():String;
function set accName(value:String):void;
function get actionScript():String;
function set actionScript(value:String):void;
function get description():String;
function set description(value:String):void;
function get forceSimple():Boolean;
function set forceSimple(value:Boolean):void;
function get shortcut():String;
function set shortcut(value:String):void;
function get silent():Boolean;
function set silent(value:Boolean):void;
function get tabIndex():Number;
function set tabIndex(value:Number):void;
}
}