// generated by dts2as from NextGenActionScript.com
package 
{
public interface FlashTimeline
{
function get currentFrame():Number;
function set currentFrame(value:Number):void;
function get currentLayer():Number;
function set currentLayer(value:Number):void;
function get frameCount():Number;
function set frameCount(value:Number):void;
function get layerCount():Number;
function set layerCount(value:Number):void;
function get layers():Array;
function set layers(value:Array):void;
function get name():String;
function set name(value:String):void;
function get libraryItem():FlashItem;
function set libraryItem(value:FlashItem):void;
function addMotionGuide():Number;
function addNewLayer(name:String = undefined, layerType:String = undefined, bAddAbove:Boolean = undefined):void;
function clearFrames(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function clearKeyframes(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function convertToBlankKeyframes(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function convertToKeyframes(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function copyFrames(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function copyLayers(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function copyMotion():void;
function copyMotionAsAS3():void;
function createMotionObject(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function createMotionTween(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function cutFrames(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function cutLayers(startLayerIndex:Number = undefined, endLayerIndex:Number = undefined):void;
function deleteLayer(index:Number):void;
function duplicateLayers(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function expandFolder(bExpand:Boolean, bRecurseNestedParents:Boolean = undefined, index:Number = undefined):void;
function findLayerIndex(name:String):Array;
function getFrameProperty(property:String, startframeIndex:Number = undefined, endFrameIndex:Number = undefined):Object;
function getGuidelines():String;
function getLayerProperty(property:String):Object;
function getSelectedFrames():Array;
function getSelectedLayers():Array;
function insertBlankKeyframe(frameNumIndex:Number = undefined):void;
function insertFrames(numFrames:Number = undefined, bAllLayers:Boolean = undefined, frameNumIndex:Number = undefined):void;
function insertKeyframe(frameNumIndex:Number = undefined):void;
function pasteFrames(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function pasteLayers(layerIndex:Number):Number;
function pasteMotion():void;
function removeFrames(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function removeMotionObject(startFrame:Number, endFrame:Number):void;
function reorderLayer(layerToMove:Number, layerToPutItBy:Number, bAddBefore:Boolean = undefined):void;
function reverseFrames(startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function selectAllFrames():void;
function setFrameProperty(property:String, value:Object, startFrameIndex:Number = undefined, endFrameIndex:Number = undefined):void;
function setGuidelines(xmlString:String):Boolean;
function setLayerProperty(property:String, value:Object, layersToChange:String = undefined):void;
function setSelectedFrames(startFrameIndexOrSelectionList:Object, endFrameIndexOrBReplaceCurrentSelection:Object = undefined, bReplaceCurrentSelection:Boolean = undefined):void;
function setSelectedLayers(index:Number, bReplaceCurrentSelection:Boolean = undefined):void;
function showLayerMasking(layer:Number):void;
function startPlayback():void;
function stopPlayback():void;
}
}