// generated by dts2as from NextGenActionScript.com
package 
{
public class SpriteSheetExporter
{
public function SpriteSheetExporter() {}

public function get algorithm():String { return null; }
public function set algorithm(value:String):void {}
public function get allowRotate():Boolean { return false; }
public function set allowRotate(value:Boolean):void {}
public function get allowTrimming():Boolean { return false; }
public function set allowTrimming(value:Boolean):void {}
public function get app():String { return null; }
public function set app(value:String):void {}
public function get autoSize():Boolean { return false; }
public function set autoSize(value:Boolean):void {}
public function get borderPadding():Number { return 0; }
public function set borderPadding(value:Number):void {}
public function get canBorderPad():Boolean { return false; }
public function set canBorderPad(value:Boolean):void {}
public function get canRotate():Boolean { return false; }
public function set canRotate(value:Boolean):void {}
public function get canTrim():Boolean { return false; }
public function set canTrim(value:Boolean):void {}
public function get canShapePad():Boolean { return false; }
public function set canShapePad(value:Boolean):void {}
public function get canStackDuplicateFrames():Boolean { return false; }
public function set canStackDuplicateFrames(value:Boolean):void {}
public function get format():String { return null; }
public function set format(value:String):void {}
public function get image():String { return null; }
public function set image(value:String):void {}
public function get layoutFormat():String { return null; }
public function set layoutFormat(value:String):void {}
public function get maxSheetHeight():Number { return 0; }
public function set maxSheetHeight(value:Number):void {}
public function get maxSheetWidth():Number { return 0; }
public function set maxSheetWidth(value:Number):void {}
public function get overflowed():Boolean { return false; }
public function set overflowed(value:Boolean):void {}
public function get shapePadding():Number { return 0; }
public function set shapePadding(value:Number):void {}
public function get sheetHeight():Number { return 0; }
public function set sheetHeight(value:Number):void {}
public function get sheetWidth():Number { return 0; }
public function set sheetWidth(value:Number):void {}
public function get stackDuplicateFrames():Boolean { return false; }
public function set stackDuplicateFrames(value:Boolean):void {}
public function get version():String { return null; }
public function set version(value:String):void {}

public function addBitmap(item:Object):void {}
public function addSymbol(item:Object, name:String = undefined, beginFrame:Number = undefined, endFrame:Number = undefined):void {}
public function beginExport():void {}
public function changeSymbol():void {}
public function exportSpriteSheet(fileURL:String, option:Object, writeMetaData:Boolean = undefined):String { return null; }
public function removeBitmap():void {}
public function removeSymbol():void {}
}
}